[
  {
    "Target": "cowrie/cowrie (debian 12.5)",
    "Class": "os-pkgs",
    "Type": "debian",
    "Vulnerabilities": [
      {
        "VulnerabilityID": "CVE-2023-52425",
        "PkgID": "libexpat1@2.5.0-1",
        "PkgName": "libexpat1",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libexpat1@2.5.0-1?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "2.5.0-1",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:4798828710c1729e8cc8d60d38b5a7a7c3f0a9e101ae58eaaf0d2f5674d89517"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-52425",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "expat: parsing large tokens can trigger a denial of service",
        "Description": "libexpat through 2.5.0 allows a denial of service (resource consumption) because many full reparsings are required in the case of a large token for which multiple buffer fills are needed.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-400"
        ],
        "VendorSeverity": {
          "nvd": 3,
          "redhat": 2
        },
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2023-52425",
          "https://github.com/libexpat/libexpat/pull/789",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-52425",
          "https://www.cve.org/CVERecord?id=CVE-2023-52425"
        ],
        "PublishedDate": "2024-02-04T20:15:46.063Z",
        "LastModifiedDate": "2024-02-09T02:03:16.3Z"
      },
      {
        "VulnerabilityID": "CVE-2023-52426",
        "PkgID": "libexpat1@2.5.0-1",
        "PkgName": "libexpat1",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libexpat1@2.5.0-1?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "2.5.0-1",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:4798828710c1729e8cc8d60d38b5a7a7c3f0a9e101ae58eaaf0d2f5674d89517"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-52426",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "expat: recursive XML entity expansion vulnerability",
        "Description": "libexpat through 2.5.0 allows recursive XML Entity Expansion if XML_DTD is undefined at compile time.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-776"
        ],
        "VendorSeverity": {
          "amazon": 2,
          "nvd": 2,
          "redhat": 2,
          "ubuntu": 2
        },
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 5.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 5.5
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2023-52426",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-52426",
          "https://cwe.mitre.org/data/definitions/776.html",
          "https://github.com/libexpat/libexpat/commit/0f075ec8ecb5e43f8fdca5182f8cca4703da0404",
          "https://github.com/libexpat/libexpat/pull/777",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-52426",
          "https://www.cve.org/CVERecord?id=CVE-2023-52426"
        ],
        "PublishedDate": "2024-02-04T20:15:46.12Z",
        "LastModifiedDate": "2024-02-09T02:02:39.8Z"
      },
      {
        "VulnerabilityID": "CVE-2023-4039",
        "PkgID": "libgcc-s1@12.2.0-14",
        "PkgName": "libgcc-s1",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libgcc-s1@12.2.0-14?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "12.2.0-14",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:f9a55c9614be7dce41d60a28717324de261036c9e9cf5ad0c797145b9e59755a"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-4039",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "gcc: -fstack-protector fails to guard dynamic stack allocations on ARM64",
        "Description": "\n\n**DISPUTED**A failure in the -fstack-protector feature in GCC-based toolchains \nthat target AArch64 allows an attacker to exploit an existing buffer \noverflow in dynamically-sized local variables in your application \nwithout this being detected. This stack-protector failure only applies \nto C99-style dynamically-sized local variables or those created using \nalloca(). The stack-protector operates as intended for statically-sized \nlocal variables.\n\nThe default behavior when the stack-protector \ndetects an overflow is to terminate your application, resulting in \ncontrolled loss of availability. An attacker who can exploit a buffer \noverflow without triggering the stack-protector might be able to change \nprogram flow control to cause an uncontrolled loss of availability or to\n go further and affect confidentiality or integrity. NOTE: The GCC project argues that this is a missed hardening bug and not a vulnerability by itself.\n\n\n\n\n\n",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-693"
        ],
        "VendorSeverity": {
          "amazon": 2,
          "cbl-mariner": 2,
          "nvd": 2,
          "oracle-oval": 1,
          "ubuntu": 2
        },
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N",
            "V3Score": 4.8
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2023-4039",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-4039",
          "https://developer.arm.com/Arm%20Security%20Center/GCC%20Stack%20Protector%20Vulnerability%20AArch64",
          "https://gcc.gnu.org/git/?p=gcc.git;a=blob_plain;f=SECURITY.txt",
          "https://gcc.gnu.org/pipermail/gcc-patches/2023-October/634066.html",
          "https://github.com/metaredteam/external-disclosures/security/advisories/GHSA-x7ch-h5rf-w2mf",
          "https://inbox.sourceware.org/gcc-patches/46cfa37b-56eb-344d-0745-e0d35393392d@gotplt.org",
          "https://linux.oracle.com/cve/CVE-2023-4039.html",
          "https://linux.oracle.com/errata/ELSA-2023-28766.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-4039",
          "https://rtx.meta.security/mitigation/2023/09/12/CVE-2023-4039.html",
          "https://www.cve.org/CVERecord?id=CVE-2023-4039"
        ],
        "PublishedDate": "2023-09-13T09:15:15.69Z",
        "LastModifiedDate": "2024-02-19T23:15:07.68Z"
      },
      {
        "VulnerabilityID": "CVE-2023-4039",
        "PkgID": "libgomp1@12.2.0-14",
        "PkgName": "libgomp1",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libgomp1@12.2.0-14?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "12.2.0-14",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:d76d57d94e12dfa53bcea78452aa3f14e7b90aae4304cb25b601c79b06c6f711"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-4039",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "gcc: -fstack-protector fails to guard dynamic stack allocations on ARM64",
        "Description": "\n\n**DISPUTED**A failure in the -fstack-protector feature in GCC-based toolchains \nthat target AArch64 allows an attacker to exploit an existing buffer \noverflow in dynamically-sized local variables in your application \nwithout this being detected. This stack-protector failure only applies \nto C99-style dynamically-sized local variables or those created using \nalloca(). The stack-protector operates as intended for statically-sized \nlocal variables.\n\nThe default behavior when the stack-protector \ndetects an overflow is to terminate your application, resulting in \ncontrolled loss of availability. An attacker who can exploit a buffer \noverflow without triggering the stack-protector might be able to change \nprogram flow control to cause an uncontrolled loss of availability or to\n go further and affect confidentiality or integrity. NOTE: The GCC project argues that this is a missed hardening bug and not a vulnerability by itself.\n\n\n\n\n\n",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-693"
        ],
        "VendorSeverity": {
          "amazon": 2,
          "cbl-mariner": 2,
          "nvd": 2,
          "oracle-oval": 1,
          "ubuntu": 2
        },
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N",
            "V3Score": 4.8
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2023-4039",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-4039",
          "https://developer.arm.com/Arm%20Security%20Center/GCC%20Stack%20Protector%20Vulnerability%20AArch64",
          "https://gcc.gnu.org/git/?p=gcc.git;a=blob_plain;f=SECURITY.txt",
          "https://gcc.gnu.org/pipermail/gcc-patches/2023-October/634066.html",
          "https://github.com/metaredteam/external-disclosures/security/advisories/GHSA-x7ch-h5rf-w2mf",
          "https://inbox.sourceware.org/gcc-patches/46cfa37b-56eb-344d-0745-e0d35393392d@gotplt.org",
          "https://linux.oracle.com/cve/CVE-2023-4039.html",
          "https://linux.oracle.com/errata/ELSA-2023-28766.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-4039",
          "https://rtx.meta.security/mitigation/2023/09/12/CVE-2023-4039.html",
          "https://www.cve.org/CVERecord?id=CVE-2023-4039"
        ],
        "PublishedDate": "2023-09-13T09:15:15.69Z",
        "LastModifiedDate": "2024-02-19T23:15:07.68Z"
      },
      {
        "VulnerabilityID": "CVE-2023-50495",
        "PkgID": "libncursesw6@6.4-4",
        "PkgName": "libncursesw6",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libncursesw6@6.4-4?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "6.4-4",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:6c211c073b68a418adce37e1bc9f0b118fff069a964d7e914be270993b00732c"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-50495",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "ncurses: segmentation fault via _nc_wrap_entry()",
        "Description": "NCurse v6.4-20230418 was discovered to contain a segmentation fault via the component _nc_wrap_entry().",
        "Severity": "MEDIUM",
        "VendorSeverity": {
          "amazon": 2,
          "nvd": 2,
          "redhat": 1,
          "ubuntu": 1
        },
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 6.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 6.5
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2023-50495",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-50495",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LU4MYMKFEZQ5VSCVLRIZGDQOUW3T44GT/",
          "https://lists.gnu.org/archive/html/bug-ncurses/2023-04/msg00020.html",
          "https://lists.gnu.org/archive/html/bug-ncurses/2023-04/msg00029.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-50495",
          "https://security.netapp.com/advisory/ntap-20240119-0008/",
          "https://www.cve.org/CVERecord?id=CVE-2023-50495"
        ],
        "PublishedDate": "2023-12-12T15:15:07.867Z",
        "LastModifiedDate": "2024-01-31T03:15:08.49Z"
      },
      {
        "VulnerabilityID": "CVE-2023-24329",
        "PkgID": "libpython3.11-minimal@3.11.2-6",
        "PkgName": "libpython3.11-minimal",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libpython3.11-minimal@3.11.2-6?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "3.11.2-6",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:1eed38b504562a535cc647a824825ae78166544d409c958abe494d9750744cc2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-24329",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: urllib.parse url blocklisting bypass",
        "Description": "An issue in the urllib.parse component of Python before 3.11.4 allows attackers to bypass blocklisting methods by supplying a URL that starts with blank characters.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-20"
        ],
        "VendorSeverity": {
          "alma": 3,
          "amazon": 3,
          "bitnami": 3,
          "cbl-mariner": 3,
          "nvd": 3,
          "oracle-oval": 3,
          "photon": 3,
          "redhat": 3,
          "rocky": 3,
          "ubuntu": 2
        },
        "CVSS": {
          "bitnami": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          },
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2023:3595",
          "https://access.redhat.com/security/cve/CVE-2023-24329",
          "https://bugzilla.redhat.com/2173917",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2173917",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-24329",
          "https://errata.almalinux.org/9/ALSA-2023-3595.html",
          "https://errata.rockylinux.org/RLSA-2023:3591",
          "https://github.com/python/cpython/issues/102153",
          "https://github.com/python/cpython/pull/99421",
          "https://github.com/python/cpython/pull/99446 (backport for 3.11 branch)",
          "https://linux.oracle.com/cve/CVE-2023-24329.html",
          "https://linux.oracle.com/errata/ELSA-2023-3811.html",
          "https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6PEVICI7YNGGMSL3UCMWGE66QFLATH72/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/DSL6NSOAXWBJJ67XPLSSC74MNKZF3BBO/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/EM2XLZSTXG44TMFXF4E6VTGKR2MQCW3G/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/F2NY75GFDZ5T6YPN44D3VMFT5SUVTOTG/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/GR5US3BYILYJ4SKBV6YBNPRUBAL5P2CN/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/H23OSKC6UG6IWOQAUPW74YUHWRWVXJP7/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JZTLGV2HYFF4AMYJL25VDIGAIHCU7UPA/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LWC4WGXER5P6Q75RFGL7QUTPP3N5JR7T/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MZEHSXSCMA4WWQKXT6QV7AAR6SWNZ2VP/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/O5SP4RT3RRS434ZS2HQKQJ3VZW7YPKYR/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OHHJHJRLEF3TDT2K3676CAUVRDD4CCMR/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PEUN6T22UJFXR7J5F6UUHCXXPKJ2DVHI/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PURM5CFDABEWAIWZFD2MQ7ZJGCPYSQ44/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/Q3J5N24ECS4B6MJDRO6UAYU6GPLYBDCL/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QRQHN7RWJQJHYP6E5EKESOYP5VDSHZG4/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RA2MBEEES6L46OD64OBSVUUMGKNGMOWW/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/T4IDB5OAR5Y4UK3HLMZBW4WEL2B7YFMJ/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/TZH26JGNZ5XYPZ5SAU3NKSBSPRE5OHTG/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/U2MZOJYGFCB5PPT6AKMAU72N7QOYWLBP/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/UONZWLB4QVLQIY5CPDLEUEKH6WX4VQMC/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/WTOAUJNDWZDRWVSXJ354AYZYKRMT56HU/",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-24329",
          "https://pointernull.com/security/python-url-parse-problem.html",
          "https://security.netapp.com/advisory/ntap-20230324-0004/",
          "https://ubuntu.com/security/notices/USN-5888-1",
          "https://ubuntu.com/security/notices/USN-5960-1",
          "https://ubuntu.com/security/notices/USN-6139-1",
          "https://www.cve.org/CVERecord?id=CVE-2023-24329",
          "https://www.kb.cert.org/vuls/id/127587"
        ],
        "PublishedDate": "2023-02-17T15:15:12.243Z",
        "LastModifiedDate": "2023-11-07T04:08:25.79Z"
      },
      {
        "VulnerabilityID": "CVE-2023-41105",
        "PkgID": "libpython3.11-minimal@3.11.2-6",
        "PkgName": "libpython3.11-minimal",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libpython3.11-minimal@3.11.2-6?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "3.11.2-6",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:1eed38b504562a535cc647a824825ae78166544d409c958abe494d9750744cc2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-41105",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: file path truncation at \\0 characters",
        "Description": "An issue was discovered in Python 3.11 through 3.11.4. If a path containing '\\0' bytes is passed to os.path.normpath(), the path will be truncated unexpectedly at the first '\\0' byte. There are plausible cases in which an application would have rejected a filename for security reasons in Python 3.10.x or earlier, but that filename is no longer rejected in Python 3.11.x.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-426"
        ],
        "VendorSeverity": {
          "alma": 2,
          "amazon": 3,
          "bitnami": 3,
          "nvd": 3,
          "oracle-oval": 2,
          "photon": 3,
          "redhat": 2,
          "ubuntu": 2
        },
        "CVSS": {
          "bitnami": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          },
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2023:6494",
          "https://access.redhat.com/security/cve/CVE-2023-41105",
          "https://bugzilla.redhat.com/2235795",
          "https://bugzilla.redhat.com/263261",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-41105",
          "https://errata.almalinux.org/9/ALSA-2023-6494.html",
          "https://github.com/python/cpython/issues/106242",
          "https://github.com/python/cpython/pull/107981",
          "https://github.com/python/cpython/pull/107982",
          "https://github.com/python/cpython/pull/107983",
          "https://linux.oracle.com/cve/CVE-2023-41105.html",
          "https://linux.oracle.com/errata/ELSA-2023-7024.html",
          "https://mail.python.org/archives/list/security-announce%40python.org/thread/D6CDW3ZZC5D444YGL3VQUY6D4ECMCQLD/",
          "https://mail.python.org/archives/list/security-announce@python.org/thread/D6CDW3ZZC5D444YGL3VQUY6D4ECMCQLD/",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-41105",
          "https://security.netapp.com/advisory/ntap-20231006-0015/",
          "https://ubuntu.com/security/notices/USN-6547-1",
          "https://www.cve.org/CVERecord?id=CVE-2023-41105"
        ],
        "PublishedDate": "2023-08-23T07:15:08.59Z",
        "LastModifiedDate": "2023-11-07T04:20:53.35Z"
      },
      {
        "VulnerabilityID": "CVE-2023-27043",
        "PkgID": "libpython3.11-minimal@3.11.2-6",
        "PkgName": "libpython3.11-minimal",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libpython3.11-minimal@3.11.2-6?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "3.11.2-6",
        "Status": "fix_deferred",
        "Layer": {
          "DiffID": "sha256:1eed38b504562a535cc647a824825ae78166544d409c958abe494d9750744cc2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-27043",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: Parsing errors in email/_parseaddr.py lead to incorrect value in email address part of tuple",
        "Description": "The email module of Python through 3.11.3 incorrectly parses e-mail addresses that contain a special character. The wrong portion of an RFC2822 header is identified as the value of the addr-spec. In some applications, an attacker can bypass a protection mechanism in which application access is granted only after verifying receipt of e-mail to a specific domain (e.g., only @company.example.com addresses may be used for signup). This occurs in email/_parseaddr.py in recent versions of Python.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-20"
        ],
        "VendorSeverity": {
          "alma": 2,
          "amazon": 2,
          "bitnami": 2,
          "nvd": 2,
          "oracle-oval": 2,
          "photon": 2,
          "redhat": 2,
          "rocky": 2,
          "ubuntu": 2
        },
        "CVSS": {
          "bitnami": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "V3Score": 5.3
          },
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "V3Score": 5.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "V3Score": 5.3
          }
        },
        "References": [
          "http://python.org",
          "https://access.redhat.com/articles/7051467",
          "https://access.redhat.com/errata/RHSA-2024:0466",
          "https://access.redhat.com/security/cve/CVE-2023-27043",
          "https://bugzilla.redhat.com/2196183",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2196183",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-27043",
          "https://errata.almalinux.org/9/ALSA-2024-0466.html",
          "https://errata.rockylinux.org/RLSA-2024:0256",
          "https://github.com/python/cpython/issues/102988",
          "https://github.com/python/cpython/pull/102990",
          "https://github.com/python/cpython/pull/105127",
          "https://linux.oracle.com/cve/CVE-2023-27043.html",
          "https://linux.oracle.com/errata/ELSA-2024-0466.html",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4ZAEFSFZDNBNJPNOUTLG5COISGQDLMGV/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/75DTHSTNOFFNAWHXKMDXS7EJWC6W2FUC/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ARI7VDSNTQVXRQFM6IK5GSSLEIYV4VZH/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HXYVPEZUA3465AEFX5JVFVP7KIFZMF3N/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6M5I6OQHJABNEYY555HUMMKX3Y4P25Z/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NEUNZSZ3CVSM2QWVYH3N2XGOCDWNYUA3/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ORLXS5YTKN65E2Q2NWKXMFS5FWQHRNZW/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2MAICLFDDO3QVNHTZ2OCERZQ34R2PIC/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2W2BZQIHMCKRI5FNBJERFYMS5PK6TAH/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PHVGRKQAGANCSGFI3QMYOCIMS4IFOZA5/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PU6Y2S5CBN5BWCBDAJFTGIBZLK3S2G3J/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RDDC2VOX7OQC6OHMYTVD4HLFZIV6PYBC/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SINP4OVYNB2AGDYI2GS37EMW3H3F7XPZ/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SOX7BCN6YL7B3RFPEEXPIU5CMTEHJOKR/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VZXC32CJ7TWDPJO6GY2XIQRO7JZX5FLP/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XWMBD4LNHWEXRI6YVFWJMTJQUL5WOFTS/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YQVY5C5REXWJIORJIL2FIL3ALOEJEF72/",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-27043",
          "https://python-security.readthedocs.io/vuln/email-parseaddr-realname.html",
          "https://security.netapp.com/advisory/ntap-20230601-0003/",
          "https://www.cve.org/CVERecord?id=CVE-2023-27043"
        ],
        "PublishedDate": "2023-04-19T00:15:07.973Z",
        "LastModifiedDate": "2024-02-05T07:15:07.72Z"
      },
      {
        "VulnerabilityID": "CVE-2023-40217",
        "PkgID": "libpython3.11-minimal@3.11.2-6",
        "PkgName": "libpython3.11-minimal",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libpython3.11-minimal@3.11.2-6?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "3.11.2-6",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:1eed38b504562a535cc647a824825ae78166544d409c958abe494d9750744cc2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-40217",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: TLS handshake bypass",
        "Description": "An issue was discovered in Python before 3.8.18, 3.9.x before 3.9.18, 3.10.x before 3.10.13, and 3.11.x before 3.11.5. It primarily affects servers (such as HTTP servers) that use TLS client authentication. If a TLS server-side socket is created, receives data into the socket buffer, and then is closed quickly, there is a brief window where the SSLSocket instance will detect the socket as \"not connected\" and won't initiate a handshake, but buffered data will still be readable from the socket buffer. This data will not be authenticated if the server-side TLS peer is expecting client certificate authentication, and is indistinguishable from valid TLS stream data. Data is limited in size to the amount that will fit in the buffer. (The TLS connection cannot directly be used for data exfiltration because the vulnerable code path requires that the connection be closed on initialization of the SSLSocket.)",
        "Severity": "MEDIUM",
        "VendorSeverity": {
          "alma": 3,
          "amazon": 3,
          "bitnami": 2,
          "nvd": 2,
          "oracle-oval": 3,
          "photon": 2,
          "redhat": 3,
          "rocky": 3,
          "ubuntu": 2
        },
        "CVSS": {
          "bitnami": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "V3Score": 5.3
          },
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "V3Score": 5.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:H/A:N",
            "V3Score": 8.6
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2023:5462",
          "https://access.redhat.com/security/cve/CVE-2023-40217",
          "https://bugzilla.redhat.com/2235789",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2235789",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-40217",
          "https://errata.almalinux.org/9/ALSA-2023-5462.html",
          "https://errata.rockylinux.org/RLSA-2023:5997",
          "https://github.com/python/cpython/commit/0cb0c238d520a8718e313b52cffc356a5a7561bf (main)",
          "https://github.com/python/cpython/commit/256586ab8776e4526ca594b4866b9a3492e628f1 (3.12)",
          "https://github.com/python/cpython/commit/264b1dacc67346efa0933d1e63f622676e0ed96b (3.9)",
          "https://github.com/python/cpython/commit/37d7180cb647f0bed0c1caab0037f3bc82e2af96 (3.10)",
          "https://github.com/python/cpython/commit/75a875e0df0530b75b1470d797942f90f4a718d3 (3.11)",
          "https://github.com/python/cpython/issues/108310",
          "https://github.com/python/cpython/pull/108315",
          "https://linux.oracle.com/cve/CVE-2023-40217.html",
          "https://linux.oracle.com/errata/ELSA-2023-6885.html",
          "https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html",
          "https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html",
          "https://mail.python.org/archives/list/security-announce%40python.org/thread/PEPLII27KYHLF4AK3ZQGKYNCRERG4YXY/",
          "https://mail.python.org/archives/list/security-announce@python.org/thread/PEPLII27KYHLF4AK3ZQGKYNCRERG4YXY/",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-40217",
          "https://security.netapp.com/advisory/ntap-20231006-0014/",
          "https://ubuntu.com/security/notices/USN-6513-1",
          "https://ubuntu.com/security/notices/USN-6513-2",
          "https://www.cve.org/CVERecord?id=CVE-2023-40217",
          "https://www.python.org/dev/security/"
        ],
        "PublishedDate": "2023-08-25T01:15:09.017Z",
        "LastModifiedDate": "2023-11-07T04:20:09.013Z"
      },
      {
        "VulnerabilityID": "CVE-2023-24329",
        "PkgID": "libpython3.11-stdlib@3.11.2-6",
        "PkgName": "libpython3.11-stdlib",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libpython3.11-stdlib@3.11.2-6?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "3.11.2-6",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:015f4092d2bce0d0e84cc513b226cc0599e0f0ab2502eaaa740094569e197872"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-24329",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: urllib.parse url blocklisting bypass",
        "Description": "An issue in the urllib.parse component of Python before 3.11.4 allows attackers to bypass blocklisting methods by supplying a URL that starts with blank characters.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-20"
        ],
        "VendorSeverity": {
          "alma": 3,
          "amazon": 3,
          "bitnami": 3,
          "cbl-mariner": 3,
          "nvd": 3,
          "oracle-oval": 3,
          "photon": 3,
          "redhat": 3,
          "rocky": 3,
          "ubuntu": 2
        },
        "CVSS": {
          "bitnami": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          },
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2023:3595",
          "https://access.redhat.com/security/cve/CVE-2023-24329",
          "https://bugzilla.redhat.com/2173917",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2173917",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-24329",
          "https://errata.almalinux.org/9/ALSA-2023-3595.html",
          "https://errata.rockylinux.org/RLSA-2023:3591",
          "https://github.com/python/cpython/issues/102153",
          "https://github.com/python/cpython/pull/99421",
          "https://github.com/python/cpython/pull/99446 (backport for 3.11 branch)",
          "https://linux.oracle.com/cve/CVE-2023-24329.html",
          "https://linux.oracle.com/errata/ELSA-2023-3811.html",
          "https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6PEVICI7YNGGMSL3UCMWGE66QFLATH72/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/DSL6NSOAXWBJJ67XPLSSC74MNKZF3BBO/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/EM2XLZSTXG44TMFXF4E6VTGKR2MQCW3G/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/F2NY75GFDZ5T6YPN44D3VMFT5SUVTOTG/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/GR5US3BYILYJ4SKBV6YBNPRUBAL5P2CN/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/H23OSKC6UG6IWOQAUPW74YUHWRWVXJP7/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JZTLGV2HYFF4AMYJL25VDIGAIHCU7UPA/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LWC4WGXER5P6Q75RFGL7QUTPP3N5JR7T/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MZEHSXSCMA4WWQKXT6QV7AAR6SWNZ2VP/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/O5SP4RT3RRS434ZS2HQKQJ3VZW7YPKYR/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OHHJHJRLEF3TDT2K3676CAUVRDD4CCMR/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PEUN6T22UJFXR7J5F6UUHCXXPKJ2DVHI/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PURM5CFDABEWAIWZFD2MQ7ZJGCPYSQ44/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/Q3J5N24ECS4B6MJDRO6UAYU6GPLYBDCL/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QRQHN7RWJQJHYP6E5EKESOYP5VDSHZG4/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RA2MBEEES6L46OD64OBSVUUMGKNGMOWW/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/T4IDB5OAR5Y4UK3HLMZBW4WEL2B7YFMJ/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/TZH26JGNZ5XYPZ5SAU3NKSBSPRE5OHTG/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/U2MZOJYGFCB5PPT6AKMAU72N7QOYWLBP/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/UONZWLB4QVLQIY5CPDLEUEKH6WX4VQMC/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/WTOAUJNDWZDRWVSXJ354AYZYKRMT56HU/",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-24329",
          "https://pointernull.com/security/python-url-parse-problem.html",
          "https://security.netapp.com/advisory/ntap-20230324-0004/",
          "https://ubuntu.com/security/notices/USN-5888-1",
          "https://ubuntu.com/security/notices/USN-5960-1",
          "https://ubuntu.com/security/notices/USN-6139-1",
          "https://www.cve.org/CVERecord?id=CVE-2023-24329",
          "https://www.kb.cert.org/vuls/id/127587"
        ],
        "PublishedDate": "2023-02-17T15:15:12.243Z",
        "LastModifiedDate": "2023-11-07T04:08:25.79Z"
      },
      {
        "VulnerabilityID": "CVE-2023-41105",
        "PkgID": "libpython3.11-stdlib@3.11.2-6",
        "PkgName": "libpython3.11-stdlib",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libpython3.11-stdlib@3.11.2-6?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "3.11.2-6",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:015f4092d2bce0d0e84cc513b226cc0599e0f0ab2502eaaa740094569e197872"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-41105",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: file path truncation at \\0 characters",
        "Description": "An issue was discovered in Python 3.11 through 3.11.4. If a path containing '\\0' bytes is passed to os.path.normpath(), the path will be truncated unexpectedly at the first '\\0' byte. There are plausible cases in which an application would have rejected a filename for security reasons in Python 3.10.x or earlier, but that filename is no longer rejected in Python 3.11.x.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-426"
        ],
        "VendorSeverity": {
          "alma": 2,
          "amazon": 3,
          "bitnami": 3,
          "nvd": 3,
          "oracle-oval": 2,
          "photon": 3,
          "redhat": 2,
          "ubuntu": 2
        },
        "CVSS": {
          "bitnami": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          },
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2023:6494",
          "https://access.redhat.com/security/cve/CVE-2023-41105",
          "https://bugzilla.redhat.com/2235795",
          "https://bugzilla.redhat.com/263261",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-41105",
          "https://errata.almalinux.org/9/ALSA-2023-6494.html",
          "https://github.com/python/cpython/issues/106242",
          "https://github.com/python/cpython/pull/107981",
          "https://github.com/python/cpython/pull/107982",
          "https://github.com/python/cpython/pull/107983",
          "https://linux.oracle.com/cve/CVE-2023-41105.html",
          "https://linux.oracle.com/errata/ELSA-2023-7024.html",
          "https://mail.python.org/archives/list/security-announce%40python.org/thread/D6CDW3ZZC5D444YGL3VQUY6D4ECMCQLD/",
          "https://mail.python.org/archives/list/security-announce@python.org/thread/D6CDW3ZZC5D444YGL3VQUY6D4ECMCQLD/",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-41105",
          "https://security.netapp.com/advisory/ntap-20231006-0015/",
          "https://ubuntu.com/security/notices/USN-6547-1",
          "https://www.cve.org/CVERecord?id=CVE-2023-41105"
        ],
        "PublishedDate": "2023-08-23T07:15:08.59Z",
        "LastModifiedDate": "2023-11-07T04:20:53.35Z"
      },
      {
        "VulnerabilityID": "CVE-2023-27043",
        "PkgID": "libpython3.11-stdlib@3.11.2-6",
        "PkgName": "libpython3.11-stdlib",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libpython3.11-stdlib@3.11.2-6?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "3.11.2-6",
        "Status": "fix_deferred",
        "Layer": {
          "DiffID": "sha256:015f4092d2bce0d0e84cc513b226cc0599e0f0ab2502eaaa740094569e197872"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-27043",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: Parsing errors in email/_parseaddr.py lead to incorrect value in email address part of tuple",
        "Description": "The email module of Python through 3.11.3 incorrectly parses e-mail addresses that contain a special character. The wrong portion of an RFC2822 header is identified as the value of the addr-spec. In some applications, an attacker can bypass a protection mechanism in which application access is granted only after verifying receipt of e-mail to a specific domain (e.g., only @company.example.com addresses may be used for signup). This occurs in email/_parseaddr.py in recent versions of Python.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-20"
        ],
        "VendorSeverity": {
          "alma": 2,
          "amazon": 2,
          "bitnami": 2,
          "nvd": 2,
          "oracle-oval": 2,
          "photon": 2,
          "redhat": 2,
          "rocky": 2,
          "ubuntu": 2
        },
        "CVSS": {
          "bitnami": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "V3Score": 5.3
          },
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "V3Score": 5.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "V3Score": 5.3
          }
        },
        "References": [
          "http://python.org",
          "https://access.redhat.com/articles/7051467",
          "https://access.redhat.com/errata/RHSA-2024:0466",
          "https://access.redhat.com/security/cve/CVE-2023-27043",
          "https://bugzilla.redhat.com/2196183",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2196183",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-27043",
          "https://errata.almalinux.org/9/ALSA-2024-0466.html",
          "https://errata.rockylinux.org/RLSA-2024:0256",
          "https://github.com/python/cpython/issues/102988",
          "https://github.com/python/cpython/pull/102990",
          "https://github.com/python/cpython/pull/105127",
          "https://linux.oracle.com/cve/CVE-2023-27043.html",
          "https://linux.oracle.com/errata/ELSA-2024-0466.html",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4ZAEFSFZDNBNJPNOUTLG5COISGQDLMGV/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/75DTHSTNOFFNAWHXKMDXS7EJWC6W2FUC/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ARI7VDSNTQVXRQFM6IK5GSSLEIYV4VZH/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HXYVPEZUA3465AEFX5JVFVP7KIFZMF3N/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6M5I6OQHJABNEYY555HUMMKX3Y4P25Z/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NEUNZSZ3CVSM2QWVYH3N2XGOCDWNYUA3/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ORLXS5YTKN65E2Q2NWKXMFS5FWQHRNZW/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2MAICLFDDO3QVNHTZ2OCERZQ34R2PIC/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2W2BZQIHMCKRI5FNBJERFYMS5PK6TAH/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PHVGRKQAGANCSGFI3QMYOCIMS4IFOZA5/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PU6Y2S5CBN5BWCBDAJFTGIBZLK3S2G3J/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RDDC2VOX7OQC6OHMYTVD4HLFZIV6PYBC/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SINP4OVYNB2AGDYI2GS37EMW3H3F7XPZ/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SOX7BCN6YL7B3RFPEEXPIU5CMTEHJOKR/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VZXC32CJ7TWDPJO6GY2XIQRO7JZX5FLP/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XWMBD4LNHWEXRI6YVFWJMTJQUL5WOFTS/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YQVY5C5REXWJIORJIL2FIL3ALOEJEF72/",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-27043",
          "https://python-security.readthedocs.io/vuln/email-parseaddr-realname.html",
          "https://security.netapp.com/advisory/ntap-20230601-0003/",
          "https://www.cve.org/CVERecord?id=CVE-2023-27043"
        ],
        "PublishedDate": "2023-04-19T00:15:07.973Z",
        "LastModifiedDate": "2024-02-05T07:15:07.72Z"
      },
      {
        "VulnerabilityID": "CVE-2023-40217",
        "PkgID": "libpython3.11-stdlib@3.11.2-6",
        "PkgName": "libpython3.11-stdlib",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libpython3.11-stdlib@3.11.2-6?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "3.11.2-6",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:015f4092d2bce0d0e84cc513b226cc0599e0f0ab2502eaaa740094569e197872"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-40217",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: TLS handshake bypass",
        "Description": "An issue was discovered in Python before 3.8.18, 3.9.x before 3.9.18, 3.10.x before 3.10.13, and 3.11.x before 3.11.5. It primarily affects servers (such as HTTP servers) that use TLS client authentication. If a TLS server-side socket is created, receives data into the socket buffer, and then is closed quickly, there is a brief window where the SSLSocket instance will detect the socket as \"not connected\" and won't initiate a handshake, but buffered data will still be readable from the socket buffer. This data will not be authenticated if the server-side TLS peer is expecting client certificate authentication, and is indistinguishable from valid TLS stream data. Data is limited in size to the amount that will fit in the buffer. (The TLS connection cannot directly be used for data exfiltration because the vulnerable code path requires that the connection be closed on initialization of the SSLSocket.)",
        "Severity": "MEDIUM",
        "VendorSeverity": {
          "alma": 3,
          "amazon": 3,
          "bitnami": 2,
          "nvd": 2,
          "oracle-oval": 3,
          "photon": 2,
          "redhat": 3,
          "rocky": 3,
          "ubuntu": 2
        },
        "CVSS": {
          "bitnami": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "V3Score": 5.3
          },
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "V3Score": 5.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:H/A:N",
            "V3Score": 8.6
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2023:5462",
          "https://access.redhat.com/security/cve/CVE-2023-40217",
          "https://bugzilla.redhat.com/2235789",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2235789",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-40217",
          "https://errata.almalinux.org/9/ALSA-2023-5462.html",
          "https://errata.rockylinux.org/RLSA-2023:5997",
          "https://github.com/python/cpython/commit/0cb0c238d520a8718e313b52cffc356a5a7561bf (main)",
          "https://github.com/python/cpython/commit/256586ab8776e4526ca594b4866b9a3492e628f1 (3.12)",
          "https://github.com/python/cpython/commit/264b1dacc67346efa0933d1e63f622676e0ed96b (3.9)",
          "https://github.com/python/cpython/commit/37d7180cb647f0bed0c1caab0037f3bc82e2af96 (3.10)",
          "https://github.com/python/cpython/commit/75a875e0df0530b75b1470d797942f90f4a718d3 (3.11)",
          "https://github.com/python/cpython/issues/108310",
          "https://github.com/python/cpython/pull/108315",
          "https://linux.oracle.com/cve/CVE-2023-40217.html",
          "https://linux.oracle.com/errata/ELSA-2023-6885.html",
          "https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html",
          "https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html",
          "https://mail.python.org/archives/list/security-announce%40python.org/thread/PEPLII27KYHLF4AK3ZQGKYNCRERG4YXY/",
          "https://mail.python.org/archives/list/security-announce@python.org/thread/PEPLII27KYHLF4AK3ZQGKYNCRERG4YXY/",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-40217",
          "https://security.netapp.com/advisory/ntap-20231006-0014/",
          "https://ubuntu.com/security/notices/USN-6513-1",
          "https://ubuntu.com/security/notices/USN-6513-2",
          "https://www.cve.org/CVERecord?id=CVE-2023-40217",
          "https://www.python.org/dev/security/"
        ],
        "PublishedDate": "2023-08-25T01:15:09.017Z",
        "LastModifiedDate": "2023-11-07T04:20:09.013Z"
      },
      {
        "VulnerabilityID": "CVE-2023-7104",
        "PkgID": "libsqlite3-0@3.40.1-2",
        "PkgName": "libsqlite3-0",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libsqlite3-0@3.40.1-2?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "3.40.1-2",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:a89ce9b0da2b49e9a0868bec2929d22eb7986026ee6e75ebbdb0b08ba70ac196"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-7104",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "sqlite: heap-buffer-overflow at sessionfuzz",
        "Description": "A vulnerability was found in SQLite SQLite3 up to 3.43.0 and classified as critical. This issue affects the function sessionReadRecord of the file ext/session/sqlite3session.c of the component make alltest Handler. The manipulation leads to heap-based buffer overflow. It is recommended to apply a patch to fix this issue. The associated identifier of this vulnerability is VDB-248999.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-119",
          "CWE-122"
        ],
        "VendorSeverity": {
          "alma": 2,
          "amazon": 3,
          "bitnami": 3,
          "cbl-mariner": 2,
          "nvd": 3,
          "oracle-oval": 2,
          "photon": 3,
          "redhat": 2,
          "rocky": 2,
          "ubuntu": 2
        },
        "CVSS": {
          "bitnami": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
            "V3Score": 7.3
          },
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
            "V3Score": 7.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
            "V3Score": 7.3
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2024:0465",
          "https://access.redhat.com/security/cve/CVE-2023-7104",
          "https://bugzilla.redhat.com/2256194",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2256194",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-7104",
          "https://errata.almalinux.org/9/ALSA-2024-0465.html",
          "https://errata.rockylinux.org/RLSA-2024:0253",
          "https://linux.oracle.com/cve/CVE-2023-7104.html",
          "https://linux.oracle.com/errata/ELSA-2024-0465.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AYONA2XSNFMXLAW4IHLFI5UVV3QRNG5K/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/D6C2HN4T2S6GYNTAUXLH45LQZHK7QPHP/",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-7104",
          "https://security.netapp.com/advisory/ntap-20240112-0008/",
          "https://sqlite.org/forum/forumpost/5bcbf4571c",
          "https://sqlite.org/src/info/0e4e7a05c4204b47",
          "https://ubuntu.com/security/notices/USN-6566-1",
          "https://vuldb.com/?ctiid.248999",
          "https://vuldb.com/?id.248999",
          "https://www.cve.org/CVERecord?id=CVE-2023-7104"
        ],
        "PublishedDate": "2023-12-29T10:15:13.89Z",
        "LastModifiedDate": "2024-01-12T14:15:49.607Z"
      },
      {
        "VulnerabilityID": "CVE-2024-0232",
        "PkgID": "libsqlite3-0@3.40.1-2",
        "PkgName": "libsqlite3-0",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libsqlite3-0@3.40.1-2?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "3.40.1-2",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:a89ce9b0da2b49e9a0868bec2929d22eb7986026ee6e75ebbdb0b08ba70ac196"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-0232",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "sqlite: use-after-free bug in jsonParseAddNodeArray",
        "Description": "A heap use-after-free issue has been identified in SQLite in the jsonParseAddNodeArray() function in sqlite3.c. This flaw allows a local attacker to leverage a victim to pass specially crafted malicious input to the application, potentially causing a crash and leading to a denial of service.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-416"
        ],
        "VendorSeverity": {
          "bitnami": 2,
          "nvd": 2,
          "redhat": 1
        },
        "CVSS": {
          "bitnami": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 5.5
          },
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 5.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:L/AC:H/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 4.7
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2024-0232",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2243754",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QDCMYQ3J45NHQ4EJREM3BJNNKB5BK4Y7/",
          "https://nvd.nist.gov/vuln/detail/CVE-2024-0232",
          "https://www.cve.org/CVERecord?id=CVE-2024-0232"
        ],
        "PublishedDate": "2024-01-16T14:15:48.327Z",
        "LastModifiedDate": "2024-02-23T02:15:44.76Z"
      },
      {
        "VulnerabilityID": "CVE-2023-5678",
        "PkgID": "libssl3@3.0.11-1~deb12u2",
        "PkgName": "libssl3",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libssl3@3.0.11-1~deb12u2?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "3.0.11-1~deb12u2",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:4abacc923ad4b46c14853c6b384ac384fbf178b7f23a15dfc1dbfb20308d4bc0"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-5678",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "openssl: Generating excessively long X9.42 DH keys or checking excessively long X9.42 DH keys or parameters may be very slow",
        "Description": "Issue summary: Generating excessively long X9.42 DH keys or checking\nexcessively long X9.42 DH keys or parameters may be very slow.\n\nImpact summary: Applications that use the functions DH_generate_key() to\ngenerate an X9.42 DH key may experience long delays.  Likewise, applications\nthat use DH_check_pub_key(), DH_check_pub_key_ex() or EVP_PKEY_public_check()\nto check an X9.42 DH key or X9.42 DH parameters may experience long delays.\nWhere the key or parameters that are being checked have been obtained from\nan untrusted source this may lead to a Denial of Service.\n\nWhile DH_check() performs all the necessary checks (as of CVE-2023-3817),\nDH_check_pub_key() doesn't make any of these checks, and is therefore\nvulnerable for excessively large P and Q parameters.\n\nLikewise, while DH_generate_key() performs a check for an excessively large\nP, it doesn't check for an excessively large Q.\n\nAn application that calls DH_generate_key() or DH_check_pub_key() and\nsupplies a key or parameters obtained from an untrusted source could be\nvulnerable to a Denial of Service attack.\n\nDH_generate_key() and DH_check_pub_key() are also called by a number of\nother OpenSSL functions.  An application calling any of those other\nfunctions may similarly be affected.  The other functions affected by this\nare DH_check_pub_key_ex(), EVP_PKEY_public_check(), and EVP_PKEY_generate().\n\nAlso vulnerable are the OpenSSL pkey command line application when using the\n\"-pubcheck\" option, as well as the OpenSSL genpkey command line application.\n\nThe OpenSSL SSL/TLS implementation is not affected by this issue.\n\nThe OpenSSL 3.0 and 3.1 FIPS providers are not affected by this issue.\n\n",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-754"
        ],
        "VendorSeverity": {
          "alma": 1,
          "amazon": 2,
          "cbl-mariner": 2,
          "nvd": 2,
          "oracle-oval": 2,
          "photon": 2,
          "redhat": 1,
          "ubuntu": 1
        },
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
            "V3Score": 5.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
            "V3Score": 5.3
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2023:7877",
          "https://access.redhat.com/security/cve/CVE-2023-5678",
          "https://bugzilla.redhat.com/2224962",
          "https://bugzilla.redhat.com/2227852",
          "https://bugzilla.redhat.com/2248616",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-5678",
          "https://errata.almalinux.org/8/ALSA-2023-7877.html",
          "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=34efaef6c103d636ab507a0cc34dca4d3aecc055",
          "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=710fee740904b6290fef0dd5536fbcedbc38ff0c",
          "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=db925ae2e65d0d925adef429afc37f75bd1c2017",
          "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=ddeb4b6c6d527e54ce9a99cba785c0f7776e54b6",
          "https://linux.oracle.com/cve/CVE-2023-5678.html",
          "https://linux.oracle.com/errata/ELSA-2024-12056.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-5678",
          "https://security.netapp.com/advisory/ntap-20231130-0010/",
          "https://ubuntu.com/security/notices/USN-6622-1",
          "https://ubuntu.com/security/notices/USN-6632-1",
          "https://www.cve.org/CVERecord?id=CVE-2023-5678",
          "https://www.openssl.org/news/secadv/20231106.txt"
        ],
        "PublishedDate": "2023-11-06T16:15:42.67Z",
        "LastModifiedDate": "2023-11-30T22:15:09.723Z"
      },
      {
        "VulnerabilityID": "CVE-2023-6129",
        "PkgID": "libssl3@3.0.11-1~deb12u2",
        "PkgName": "libssl3",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libssl3@3.0.11-1~deb12u2?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "3.0.11-1~deb12u2",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:4abacc923ad4b46c14853c6b384ac384fbf178b7f23a15dfc1dbfb20308d4bc0"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-6129",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "openssl: POLY1305 MAC implementation corrupts vector registers on PowerPC",
        "Description": "Issue summary: The POLY1305 MAC (message authentication code) implementation\ncontains a bug that might corrupt the internal state of applications running\non PowerPC CPU based platforms if the CPU provides vector instructions.\n\nImpact summary: If an attacker can influence whether the POLY1305 MAC\nalgorithm is used, the application state might be corrupted with various\napplication dependent consequences.\n\nThe POLY1305 MAC (message authentication code) implementation in OpenSSL for\nPowerPC CPUs restores the contents of vector registers in a different order\nthan they are saved. Thus the contents of some of these vector registers\nare corrupted when returning to the caller. The vulnerable code is used only\non newer PowerPC processors supporting the PowerISA 2.07 instructions.\n\nThe consequences of this kind of internal application state corruption can\nbe various - from no consequences, if the calling application does not\ndepend on the contents of non-volatile XMM registers at all, to the worst\nconsequences, where the attacker could get complete control of the application\nprocess. However unless the compiler uses the vector registers for storing\npointers, the most likely consequence, if any, would be an incorrect result\nof some application dependent calculations or a crash leading to a denial of\nservice.\n\nThe POLY1305 MAC algorithm is most frequently used as part of the\nCHACHA20-POLY1305 AEAD (authenticated encryption with associated data)\nalgorithm. The most common usage of this AEAD cipher is with TLS protocol\nversions 1.2 and 1.3. If this cipher is enabled on the server a malicious\nclient can influence whether this AEAD cipher is used. This implies that\nTLS server applications using OpenSSL can be potentially impacted. However\nwe are currently not aware of any concrete application that would be affected\nby this issue therefore we consider this a Low severity security issue.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-787"
        ],
        "VendorSeverity": {
          "nvd": 2,
          "redhat": 1,
          "ubuntu": 1
        },
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:H",
            "V3Score": 6.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:H",
            "V3Score": 6.5
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2023-6129",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-6129",
          "https://github.com/openssl/openssl/commit/050d26383d4e264966fb83428e72d5d48f402d35",
          "https://github.com/openssl/openssl/commit/5b139f95c9a47a55a0c54100f3837b1eee942b04",
          "https://github.com/openssl/openssl/commit/f3fc5808fe9ff74042d639839610d03b8fdcc015",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-6129",
          "https://security.netapp.com/advisory/ntap-20240216-0009/",
          "https://ubuntu.com/security/notices/USN-6622-1",
          "https://www.cve.org/CVERecord?id=CVE-2023-6129",
          "https://www.openssl.org/news/secadv/20240109.txt",
          "https://www.openwall.com/lists/oss-security/2024/01/09/1"
        ],
        "PublishedDate": "2024-01-09T17:15:12.147Z",
        "LastModifiedDate": "2024-02-16T13:15:09.91Z"
      },
      {
        "VulnerabilityID": "CVE-2023-6237",
        "PkgID": "libssl3@3.0.11-1~deb12u2",
        "PkgName": "libssl3",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libssl3@3.0.11-1~deb12u2?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "3.0.11-1~deb12u2",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:4abacc923ad4b46c14853c6b384ac384fbf178b7f23a15dfc1dbfb20308d4bc0"
        },
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-6237",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "openssl: Excessive time spent checking invalid RSA public keys",
        "Description": "A flaw was found in OpenSSL. When the EVP_PKEY_public_check() function is called in RSA public keys, a computation is done to confirm that the RSA modulus, n, is composite. For valid RSA keys, n is a product of two or more large primes and this computation completes quickly. However, if n is a large prime, this computation takes a long time. An application that calls EVP_PKEY_public_check() and supplies an RSA key obtained from an untrusted source could be vulnerable to a Denial of Service attack.",
        "Severity": "MEDIUM",
        "VendorSeverity": {
          "amazon": 2,
          "redhat": 1,
          "ubuntu": 1
        },
        "CVSS": {
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 5.9
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2023-6237",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-6237",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-6237",
          "https://ubuntu.com/security/notices/USN-6622-1",
          "https://www.cve.org/CVERecord?id=CVE-2023-6237",
          "https://www.openssl.org/news/secadv/20240115.txt",
          "https://www.openwall.com/lists/oss-security/2024/01/15/2"
        ]
      },
      {
        "VulnerabilityID": "CVE-2024-0727",
        "PkgID": "libssl3@3.0.11-1~deb12u2",
        "PkgName": "libssl3",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libssl3@3.0.11-1~deb12u2?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "3.0.11-1~deb12u2",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:4abacc923ad4b46c14853c6b384ac384fbf178b7f23a15dfc1dbfb20308d4bc0"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-0727",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "openssl: denial of service via null dereference",
        "Description": "Issue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.",
        "Severity": "MEDIUM",
        "VendorSeverity": {
          "amazon": 2,
          "ghsa": 2,
          "nvd": 2,
          "photon": 2,
          "redhat": 1,
          "ubuntu": 1
        },
        "CVSS": {
          "ghsa": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 5.5
          },
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 5.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 5.5
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2024-0727",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-0727",
          "https://github.com/alexcrichton/openssl-src-rs/commit/add20f73b6b42be7451af2e1044d4e0e778992b2",
          "https://github.com/github/advisory-database/pull/3472",
          "https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2",
          "https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a",
          "https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c",
          "https://github.com/openssl/openssl/pull/23362",
          "https://github.com/pyca/cryptography/commit/3519591d255d4506fbcd0d04037d45271903c64d",
          "https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8",
          "https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539",
          "https://nvd.nist.gov/vuln/detail/CVE-2024-0727",
          "https://security.netapp.com/advisory/ntap-20240208-0006",
          "https://security.netapp.com/advisory/ntap-20240208-0006/",
          "https://ubuntu.com/security/notices/USN-6622-1",
          "https://ubuntu.com/security/notices/USN-6632-1",
          "https://www.cve.org/CVERecord?id=CVE-2024-0727",
          "https://www.openssl.org/news/secadv/20240125.txt"
        ],
        "PublishedDate": "2024-01-26T09:15:07.637Z",
        "LastModifiedDate": "2024-02-08T10:15:13.91Z"
      },
      {
        "VulnerabilityID": "CVE-2023-4039",
        "PkgID": "libstdc++6@12.2.0-14",
        "PkgName": "libstdc++6",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libstdc%2B%2B6@12.2.0-14?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "12.2.0-14",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:694893867b688a6706e76ae80092a67f996a4b293d08158de07bbcbfc63c8ed3"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-4039",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "gcc: -fstack-protector fails to guard dynamic stack allocations on ARM64",
        "Description": "\n\n**DISPUTED**A failure in the -fstack-protector feature in GCC-based toolchains \nthat target AArch64 allows an attacker to exploit an existing buffer \noverflow in dynamically-sized local variables in your application \nwithout this being detected. This stack-protector failure only applies \nto C99-style dynamically-sized local variables or those created using \nalloca(). The stack-protector operates as intended for statically-sized \nlocal variables.\n\nThe default behavior when the stack-protector \ndetects an overflow is to terminate your application, resulting in \ncontrolled loss of availability. An attacker who can exploit a buffer \noverflow without triggering the stack-protector might be able to change \nprogram flow control to cause an uncontrolled loss of availability or to\n go further and affect confidentiality or integrity. NOTE: The GCC project argues that this is a missed hardening bug and not a vulnerability by itself.\n\n\n\n\n\n",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-693"
        ],
        "VendorSeverity": {
          "amazon": 2,
          "cbl-mariner": 2,
          "nvd": 2,
          "oracle-oval": 1,
          "ubuntu": 2
        },
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N",
            "V3Score": 4.8
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2023-4039",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-4039",
          "https://developer.arm.com/Arm%20Security%20Center/GCC%20Stack%20Protector%20Vulnerability%20AArch64",
          "https://gcc.gnu.org/git/?p=gcc.git;a=blob_plain;f=SECURITY.txt",
          "https://gcc.gnu.org/pipermail/gcc-patches/2023-October/634066.html",
          "https://github.com/metaredteam/external-disclosures/security/advisories/GHSA-x7ch-h5rf-w2mf",
          "https://inbox.sourceware.org/gcc-patches/46cfa37b-56eb-344d-0745-e0d35393392d@gotplt.org",
          "https://linux.oracle.com/cve/CVE-2023-4039.html",
          "https://linux.oracle.com/errata/ELSA-2023-28766.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-4039",
          "https://rtx.meta.security/mitigation/2023/09/12/CVE-2023-4039.html",
          "https://www.cve.org/CVERecord?id=CVE-2023-4039"
        ],
        "PublishedDate": "2023-09-13T09:15:15.69Z",
        "LastModifiedDate": "2024-02-19T23:15:07.68Z"
      },
      {
        "VulnerabilityID": "CVE-2023-50495",
        "PkgID": "libtinfo6@6.4-4",
        "PkgName": "libtinfo6",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/libtinfo6@6.4-4?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "6.4-4",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:cc7fea07fe820adac1ffe306417c4b58064cc2138cdc741a2a53321ec2f24310"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-50495",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "ncurses: segmentation fault via _nc_wrap_entry()",
        "Description": "NCurse v6.4-20230418 was discovered to contain a segmentation fault via the component _nc_wrap_entry().",
        "Severity": "MEDIUM",
        "VendorSeverity": {
          "amazon": 2,
          "nvd": 2,
          "redhat": 1,
          "ubuntu": 1
        },
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 6.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 6.5
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2023-50495",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-50495",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LU4MYMKFEZQ5VSCVLRIZGDQOUW3T44GT/",
          "https://lists.gnu.org/archive/html/bug-ncurses/2023-04/msg00020.html",
          "https://lists.gnu.org/archive/html/bug-ncurses/2023-04/msg00029.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-50495",
          "https://security.netapp.com/advisory/ntap-20240119-0008/",
          "https://www.cve.org/CVERecord?id=CVE-2023-50495"
        ],
        "PublishedDate": "2023-12-12T15:15:07.867Z",
        "LastModifiedDate": "2024-01-31T03:15:08.49Z"
      },
      {
        "VulnerabilityID": "CVE-2023-24329",
        "PkgID": "python3.11-minimal@3.11.2-6",
        "PkgName": "python3.11-minimal",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/python3.11-minimal@3.11.2-6?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "3.11.2-6",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:f9b5004061fd34fdfb15a7a42835e70e446f14471a2719bd041a637467966e8b"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-24329",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: urllib.parse url blocklisting bypass",
        "Description": "An issue in the urllib.parse component of Python before 3.11.4 allows attackers to bypass blocklisting methods by supplying a URL that starts with blank characters.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-20"
        ],
        "VendorSeverity": {
          "alma": 3,
          "amazon": 3,
          "bitnami": 3,
          "cbl-mariner": 3,
          "nvd": 3,
          "oracle-oval": 3,
          "photon": 3,
          "redhat": 3,
          "rocky": 3,
          "ubuntu": 2
        },
        "CVSS": {
          "bitnami": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          },
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2023:3595",
          "https://access.redhat.com/security/cve/CVE-2023-24329",
          "https://bugzilla.redhat.com/2173917",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2173917",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-24329",
          "https://errata.almalinux.org/9/ALSA-2023-3595.html",
          "https://errata.rockylinux.org/RLSA-2023:3591",
          "https://github.com/python/cpython/issues/102153",
          "https://github.com/python/cpython/pull/99421",
          "https://github.com/python/cpython/pull/99446 (backport for 3.11 branch)",
          "https://linux.oracle.com/cve/CVE-2023-24329.html",
          "https://linux.oracle.com/errata/ELSA-2023-3811.html",
          "https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6PEVICI7YNGGMSL3UCMWGE66QFLATH72/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/DSL6NSOAXWBJJ67XPLSSC74MNKZF3BBO/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/EM2XLZSTXG44TMFXF4E6VTGKR2MQCW3G/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/F2NY75GFDZ5T6YPN44D3VMFT5SUVTOTG/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/GR5US3BYILYJ4SKBV6YBNPRUBAL5P2CN/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/H23OSKC6UG6IWOQAUPW74YUHWRWVXJP7/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JZTLGV2HYFF4AMYJL25VDIGAIHCU7UPA/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LWC4WGXER5P6Q75RFGL7QUTPP3N5JR7T/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MZEHSXSCMA4WWQKXT6QV7AAR6SWNZ2VP/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/O5SP4RT3RRS434ZS2HQKQJ3VZW7YPKYR/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OHHJHJRLEF3TDT2K3676CAUVRDD4CCMR/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PEUN6T22UJFXR7J5F6UUHCXXPKJ2DVHI/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PURM5CFDABEWAIWZFD2MQ7ZJGCPYSQ44/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/Q3J5N24ECS4B6MJDRO6UAYU6GPLYBDCL/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QRQHN7RWJQJHYP6E5EKESOYP5VDSHZG4/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RA2MBEEES6L46OD64OBSVUUMGKNGMOWW/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/T4IDB5OAR5Y4UK3HLMZBW4WEL2B7YFMJ/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/TZH26JGNZ5XYPZ5SAU3NKSBSPRE5OHTG/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/U2MZOJYGFCB5PPT6AKMAU72N7QOYWLBP/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/UONZWLB4QVLQIY5CPDLEUEKH6WX4VQMC/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/WTOAUJNDWZDRWVSXJ354AYZYKRMT56HU/",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-24329",
          "https://pointernull.com/security/python-url-parse-problem.html",
          "https://security.netapp.com/advisory/ntap-20230324-0004/",
          "https://ubuntu.com/security/notices/USN-5888-1",
          "https://ubuntu.com/security/notices/USN-5960-1",
          "https://ubuntu.com/security/notices/USN-6139-1",
          "https://www.cve.org/CVERecord?id=CVE-2023-24329",
          "https://www.kb.cert.org/vuls/id/127587"
        ],
        "PublishedDate": "2023-02-17T15:15:12.243Z",
        "LastModifiedDate": "2023-11-07T04:08:25.79Z"
      },
      {
        "VulnerabilityID": "CVE-2023-41105",
        "PkgID": "python3.11-minimal@3.11.2-6",
        "PkgName": "python3.11-minimal",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/python3.11-minimal@3.11.2-6?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "3.11.2-6",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:f9b5004061fd34fdfb15a7a42835e70e446f14471a2719bd041a637467966e8b"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-41105",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: file path truncation at \\0 characters",
        "Description": "An issue was discovered in Python 3.11 through 3.11.4. If a path containing '\\0' bytes is passed to os.path.normpath(), the path will be truncated unexpectedly at the first '\\0' byte. There are plausible cases in which an application would have rejected a filename for security reasons in Python 3.10.x or earlier, but that filename is no longer rejected in Python 3.11.x.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-426"
        ],
        "VendorSeverity": {
          "alma": 2,
          "amazon": 3,
          "bitnami": 3,
          "nvd": 3,
          "oracle-oval": 2,
          "photon": 3,
          "redhat": 2,
          "ubuntu": 2
        },
        "CVSS": {
          "bitnami": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          },
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2023:6494",
          "https://access.redhat.com/security/cve/CVE-2023-41105",
          "https://bugzilla.redhat.com/2235795",
          "https://bugzilla.redhat.com/263261",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-41105",
          "https://errata.almalinux.org/9/ALSA-2023-6494.html",
          "https://github.com/python/cpython/issues/106242",
          "https://github.com/python/cpython/pull/107981",
          "https://github.com/python/cpython/pull/107982",
          "https://github.com/python/cpython/pull/107983",
          "https://linux.oracle.com/cve/CVE-2023-41105.html",
          "https://linux.oracle.com/errata/ELSA-2023-7024.html",
          "https://mail.python.org/archives/list/security-announce%40python.org/thread/D6CDW3ZZC5D444YGL3VQUY6D4ECMCQLD/",
          "https://mail.python.org/archives/list/security-announce@python.org/thread/D6CDW3ZZC5D444YGL3VQUY6D4ECMCQLD/",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-41105",
          "https://security.netapp.com/advisory/ntap-20231006-0015/",
          "https://ubuntu.com/security/notices/USN-6547-1",
          "https://www.cve.org/CVERecord?id=CVE-2023-41105"
        ],
        "PublishedDate": "2023-08-23T07:15:08.59Z",
        "LastModifiedDate": "2023-11-07T04:20:53.35Z"
      },
      {
        "VulnerabilityID": "CVE-2023-27043",
        "PkgID": "python3.11-minimal@3.11.2-6",
        "PkgName": "python3.11-minimal",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/python3.11-minimal@3.11.2-6?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "3.11.2-6",
        "Status": "fix_deferred",
        "Layer": {
          "DiffID": "sha256:f9b5004061fd34fdfb15a7a42835e70e446f14471a2719bd041a637467966e8b"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-27043",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: Parsing errors in email/_parseaddr.py lead to incorrect value in email address part of tuple",
        "Description": "The email module of Python through 3.11.3 incorrectly parses e-mail addresses that contain a special character. The wrong portion of an RFC2822 header is identified as the value of the addr-spec. In some applications, an attacker can bypass a protection mechanism in which application access is granted only after verifying receipt of e-mail to a specific domain (e.g., only @company.example.com addresses may be used for signup). This occurs in email/_parseaddr.py in recent versions of Python.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-20"
        ],
        "VendorSeverity": {
          "alma": 2,
          "amazon": 2,
          "bitnami": 2,
          "nvd": 2,
          "oracle-oval": 2,
          "photon": 2,
          "redhat": 2,
          "rocky": 2,
          "ubuntu": 2
        },
        "CVSS": {
          "bitnami": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "V3Score": 5.3
          },
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "V3Score": 5.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "V3Score": 5.3
          }
        },
        "References": [
          "http://python.org",
          "https://access.redhat.com/articles/7051467",
          "https://access.redhat.com/errata/RHSA-2024:0466",
          "https://access.redhat.com/security/cve/CVE-2023-27043",
          "https://bugzilla.redhat.com/2196183",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2196183",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-27043",
          "https://errata.almalinux.org/9/ALSA-2024-0466.html",
          "https://errata.rockylinux.org/RLSA-2024:0256",
          "https://github.com/python/cpython/issues/102988",
          "https://github.com/python/cpython/pull/102990",
          "https://github.com/python/cpython/pull/105127",
          "https://linux.oracle.com/cve/CVE-2023-27043.html",
          "https://linux.oracle.com/errata/ELSA-2024-0466.html",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4ZAEFSFZDNBNJPNOUTLG5COISGQDLMGV/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/75DTHSTNOFFNAWHXKMDXS7EJWC6W2FUC/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ARI7VDSNTQVXRQFM6IK5GSSLEIYV4VZH/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HXYVPEZUA3465AEFX5JVFVP7KIFZMF3N/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6M5I6OQHJABNEYY555HUMMKX3Y4P25Z/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NEUNZSZ3CVSM2QWVYH3N2XGOCDWNYUA3/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ORLXS5YTKN65E2Q2NWKXMFS5FWQHRNZW/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2MAICLFDDO3QVNHTZ2OCERZQ34R2PIC/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2W2BZQIHMCKRI5FNBJERFYMS5PK6TAH/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PHVGRKQAGANCSGFI3QMYOCIMS4IFOZA5/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PU6Y2S5CBN5BWCBDAJFTGIBZLK3S2G3J/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RDDC2VOX7OQC6OHMYTVD4HLFZIV6PYBC/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SINP4OVYNB2AGDYI2GS37EMW3H3F7XPZ/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SOX7BCN6YL7B3RFPEEXPIU5CMTEHJOKR/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VZXC32CJ7TWDPJO6GY2XIQRO7JZX5FLP/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XWMBD4LNHWEXRI6YVFWJMTJQUL5WOFTS/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YQVY5C5REXWJIORJIL2FIL3ALOEJEF72/",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-27043",
          "https://python-security.readthedocs.io/vuln/email-parseaddr-realname.html",
          "https://security.netapp.com/advisory/ntap-20230601-0003/",
          "https://www.cve.org/CVERecord?id=CVE-2023-27043"
        ],
        "PublishedDate": "2023-04-19T00:15:07.973Z",
        "LastModifiedDate": "2024-02-05T07:15:07.72Z"
      },
      {
        "VulnerabilityID": "CVE-2023-40217",
        "PkgID": "python3.11-minimal@3.11.2-6",
        "PkgName": "python3.11-minimal",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/python3.11-minimal@3.11.2-6?arch=amd64&distro=debian-12.5"
        },
        "InstalledVersion": "3.11.2-6",
        "Status": "affected",
        "Layer": {
          "DiffID": "sha256:f9b5004061fd34fdfb15a7a42835e70e446f14471a2719bd041a637467966e8b"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-40217",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: TLS handshake bypass",
        "Description": "An issue was discovered in Python before 3.8.18, 3.9.x before 3.9.18, 3.10.x before 3.10.13, and 3.11.x before 3.11.5. It primarily affects servers (such as HTTP servers) that use TLS client authentication. If a TLS server-side socket is created, receives data into the socket buffer, and then is closed quickly, there is a brief window where the SSLSocket instance will detect the socket as \"not connected\" and won't initiate a handshake, but buffered data will still be readable from the socket buffer. This data will not be authenticated if the server-side TLS peer is expecting client certificate authentication, and is indistinguishable from valid TLS stream data. Data is limited in size to the amount that will fit in the buffer. (The TLS connection cannot directly be used for data exfiltration because the vulnerable code path requires that the connection be closed on initialization of the SSLSocket.)",
        "Severity": "MEDIUM",
        "VendorSeverity": {
          "alma": 3,
          "amazon": 3,
          "bitnami": 2,
          "nvd": 2,
          "oracle-oval": 3,
          "photon": 2,
          "redhat": 3,
          "rocky": 3,
          "ubuntu": 2
        },
        "CVSS": {
          "bitnami": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "V3Score": 5.3
          },
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "V3Score": 5.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:H/A:N",
            "V3Score": 8.6
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2023:5462",
          "https://access.redhat.com/security/cve/CVE-2023-40217",
          "https://bugzilla.redhat.com/2235789",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2235789",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-40217",
          "https://errata.almalinux.org/9/ALSA-2023-5462.html",
          "https://errata.rockylinux.org/RLSA-2023:5997",
          "https://github.com/python/cpython/commit/0cb0c238d520a8718e313b52cffc356a5a7561bf (main)",
          "https://github.com/python/cpython/commit/256586ab8776e4526ca594b4866b9a3492e628f1 (3.12)",
          "https://github.com/python/cpython/commit/264b1dacc67346efa0933d1e63f622676e0ed96b (3.9)",
          "https://github.com/python/cpython/commit/37d7180cb647f0bed0c1caab0037f3bc82e2af96 (3.10)",
          "https://github.com/python/cpython/commit/75a875e0df0530b75b1470d797942f90f4a718d3 (3.11)",
          "https://github.com/python/cpython/issues/108310",
          "https://github.com/python/cpython/pull/108315",
          "https://linux.oracle.com/cve/CVE-2023-40217.html",
          "https://linux.oracle.com/errata/ELSA-2023-6885.html",
          "https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html",
          "https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html",
          "https://mail.python.org/archives/list/security-announce%40python.org/thread/PEPLII27KYHLF4AK3ZQGKYNCRERG4YXY/",
          "https://mail.python.org/archives/list/security-announce@python.org/thread/PEPLII27KYHLF4AK3ZQGKYNCRERG4YXY/",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-40217",
          "https://security.netapp.com/advisory/ntap-20231006-0014/",
          "https://ubuntu.com/security/notices/USN-6513-1",
          "https://ubuntu.com/security/notices/USN-6513-2",
          "https://www.cve.org/CVERecord?id=CVE-2023-40217",
          "https://www.python.org/dev/security/"
        ],
        "PublishedDate": "2023-08-25T01:15:09.017Z",
        "LastModifiedDate": "2023-11-07T04:20:09.013Z"
      },
      {
        "VulnerabilityID": "CVE-2023-45853",
        "PkgID": "zlib1g@1:1.2.13.dfsg-1",
        "PkgName": "zlib1g",
        "PkgIdentifier": {
          "PURL": "pkg:deb/debian/zlib1g@1.2.13.dfsg-1?arch=amd64&distro=debian-12.5&epoch=1"
        },
        "InstalledVersion": "1:1.2.13.dfsg-1",
        "Status": "will_not_fix",
        "Layer": {
          "DiffID": "sha256:823445a9cbb6a131bc85d47351491ef2aab9093efb417071e2eec55be2a55ceb"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-45853",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "zlib: integer overflow and resultant heap-based buffer overflow in zipOpenNewFileInZip4_6",
        "Description": "MiniZip in zlib through 1.3 has an integer overflow and resultant heap-based buffer overflow in zipOpenNewFileInZip4_64 via a long filename, comment, or extra field. NOTE: MiniZip is not a supported part of the zlib product. NOTE: pyminizip through 0.2.6 is also vulnerable because it bundles an affected zlib version, and exposes the applicable MiniZip code through its compress API.",
        "Severity": "CRITICAL",
        "CweIDs": [
          "CWE-190"
        ],
        "VendorSeverity": {
          "amazon": 2,
          "cbl-mariner": 4,
          "ghsa": 4,
          "nvd": 4,
          "photon": 4,
          "redhat": 2,
          "ubuntu": 2
        },
        "CVSS": {
          "ghsa": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 9.8
          },
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 9.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:L",
            "V3Score": 5.3
          }
        },
        "References": [
          "http://www.openwall.com/lists/oss-security/2023/10/20/9",
          "http://www.openwall.com/lists/oss-security/2024/01/24/10",
          "https://access.redhat.com/security/cve/CVE-2023-45853",
          "https://chromium.googlesource.com/chromium/src/+/d709fb23806858847131027da95ef4c548813356",
          "https://chromium.googlesource.com/chromium/src/+/de29dd6c7151d3cd37cb4cf0036800ddfb1d8b61",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-45853",
          "https://github.com/madler/zlib/blob/ac8f12c97d1afd9bafa9c710f827d40a407d3266/contrib/README.contrib#L1-L4",
          "https://github.com/madler/zlib/commit/73331a6a0481067628f065ffe87bb1d8f787d10c",
          "https://github.com/madler/zlib/pull/843",
          "https://github.com/smihica/pyminizip",
          "https://github.com/smihica/pyminizip/blob/master/zlib-1.2.11/contrib/minizip/zip.c",
          "https://lists.debian.org/debian-lts-announce/2023/11/msg00026.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-45853",
          "https://pypi.org/project/pyminizip/#history",
          "https://security.gentoo.org/glsa/202401-18",
          "https://security.netapp.com/advisory/ntap-20231130-0009",
          "https://security.netapp.com/advisory/ntap-20231130-0009/",
          "https://www.cve.org/CVERecord?id=CVE-2023-45853",
          "https://www.winimage.com/zLibDll/minizip.html"
        ],
        "PublishedDate": "2023-10-14T02:15:09.323Z",
        "LastModifiedDate": "2024-01-24T21:15:08.623Z"
      }
    ]
  },
  {
    "Target": "Python",
    "Class": "lang-pkgs",
    "Type": "python-pkg",
    "Vulnerabilities": [
      {
        "VulnerabilityID": "CVE-2023-50782",
        "PkgName": "cryptography",
        "PkgPath": "cowrie/cowrie-env/lib/python3.11/site-packages/cryptography-41.0.7.dist-info/METADATA",
        "PkgIdentifier": {
          "PURL": "pkg:pypi/cryptography@41.0.7"
        },
        "InstalledVersion": "41.0.7",
        "FixedVersion": "42.0.0",
        "Status": "fixed",
        "Layer": {
          "DiffID": "sha256:af19757e756c95e493d24b4663972d83916977f29efc4fdb5db1bb7f346c7039"
        },
        "SeveritySource": "ghsa",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-50782",
        "DataSource": {
          "ID": "ghsa",
          "Name": "GitHub Security Advisory pip",
          "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
        },
        "Title": "python-cryptography: Bleichenbacher timing oracle attack against RSA decryption - incomplete fix for CVE-2020-25659",
        "Description": "A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-203",
          "CWE-208"
        ],
        "VendorSeverity": {
          "ghsa": 3,
          "nvd": 3,
          "redhat": 2,
          "ubuntu": 2
        },
        "CVSS": {
          "ghsa": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
            "V3Score": 7.5
          },
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2023-50782",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2254432",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-50782",
          "https://github.com/openssl/openssl/pull/13817",
          "https://github.com/pyca/cryptography",
          "https://github.com/pyca/cryptography/issues/9785",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-50782",
          "https://people.redhat.com/~hkario/marvin/",
          "https://www.cve.org/CVERecord?id=CVE-2023-50782"
        ],
        "PublishedDate": "2024-02-05T21:15:11.183Z",
        "LastModifiedDate": "2024-02-14T17:52:10.027Z"
      },
      {
        "VulnerabilityID": "CVE-2024-26130",
        "PkgName": "cryptography",
        "PkgPath": "cowrie/cowrie-env/lib/python3.11/site-packages/cryptography-41.0.7.dist-info/METADATA",
        "PkgIdentifier": {
          "PURL": "pkg:pypi/cryptography@41.0.7"
        },
        "InstalledVersion": "41.0.7",
        "FixedVersion": "42.0.4",
        "Status": "fixed",
        "Layer": {
          "DiffID": "sha256:af19757e756c95e493d24b4663972d83916977f29efc4fdb5db1bb7f346c7039"
        },
        "SeveritySource": "ghsa",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-26130",
        "DataSource": {
          "ID": "ghsa",
          "Name": "GitHub Security Advisory pip",
          "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
        },
        "Title": "cryptography is a package designed to expose cryptographic primitives  ...",
        "Description": "cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Starting in version 38.0.0 and prior to version 42.0.4, if `pkcs12.serialize_key_and_certificates` is called with both a certificate whose public key did not match the provided private key and an `encryption_algorithm` with `hmac_hash` set (via `PrivateFormat.PKCS12.encryption_builder().hmac_hash(...)`, then a NULL pointer dereference would occur, crashing the Python process. This has been resolved in version 42.0.4, the first version in which a `ValueError` is properly raised.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-476"
        ],
        "VendorSeverity": {
          "ghsa": 3
        },
        "CVSS": {
          "ghsa": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://github.com/pyca/cryptography",
          "https://github.com/pyca/cryptography/commit/97d231672763cdb5959a3b191e692a362f1b9e55",
          "https://github.com/pyca/cryptography/pull/10423",
          "https://github.com/pyca/cryptography/security/advisories/GHSA-6vqw-3v5j-54x4",
          "https://nvd.nist.gov/vuln/detail/CVE-2024-26130"
        ],
        "PublishedDate": "2024-02-21T17:15:09.863Z",
        "LastModifiedDate": "2024-02-22T19:07:27.197Z"
      },
      {
        "VulnerabilityID": "CVE-2024-0727",
        "PkgName": "cryptography",
        "PkgPath": "cowrie/cowrie-env/lib/python3.11/site-packages/cryptography-41.0.7.dist-info/METADATA",
        "PkgIdentifier": {
          "PURL": "pkg:pypi/cryptography@41.0.7"
        },
        "InstalledVersion": "41.0.7",
        "FixedVersion": "42.0.2",
        "Status": "fixed",
        "Layer": {
          "DiffID": "sha256:af19757e756c95e493d24b4663972d83916977f29efc4fdb5db1bb7f346c7039"
        },
        "SeveritySource": "ghsa",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-0727",
        "DataSource": {
          "ID": "ghsa",
          "Name": "GitHub Security Advisory pip",
          "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
        },
        "Title": "openssl: denial of service via null dereference",
        "Description": "Issue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.",
        "Severity": "MEDIUM",
        "VendorSeverity": {
          "amazon": 2,
          "ghsa": 2,
          "nvd": 2,
          "photon": 2,
          "redhat": 1,
          "ubuntu": 1
        },
        "CVSS": {
          "ghsa": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 5.5
          },
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 5.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 5.5
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2024-0727",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-0727",
          "https://github.com/alexcrichton/openssl-src-rs/commit/add20f73b6b42be7451af2e1044d4e0e778992b2",
          "https://github.com/github/advisory-database/pull/3472",
          "https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2",
          "https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a",
          "https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c",
          "https://github.com/openssl/openssl/pull/23362",
          "https://github.com/pyca/cryptography/commit/3519591d255d4506fbcd0d04037d45271903c64d",
          "https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8",
          "https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539",
          "https://nvd.nist.gov/vuln/detail/CVE-2024-0727",
          "https://security.netapp.com/advisory/ntap-20240208-0006",
          "https://security.netapp.com/advisory/ntap-20240208-0006/",
          "https://ubuntu.com/security/notices/USN-6622-1",
          "https://ubuntu.com/security/notices/USN-6632-1",
          "https://www.cve.org/CVERecord?id=CVE-2024-0727",
          "https://www.openssl.org/news/secadv/20240125.txt"
        ],
        "PublishedDate": "2024-01-26T09:15:07.637Z",
        "LastModifiedDate": "2024-02-08T10:15:13.91Z"
      }
    ]
  }
]