[
  {
    "Target": "cowrie/cowrie (debian 11.7)",
    "Class": "os-pkgs",
    "Type": "debian",
    "Vulnerabilities": [
      {
        "VulnerabilityID": "CVE-2022-1304",
        "PkgID": "libcom-err2@1.46.2-2",
        "PkgName": "libcom-err2",
        "InstalledVersion": "1.46.2-2",
        "Layer": {
          "DiffID": "sha256:ca4eecbf39e6758abf787dd9fab38148e03aefbb5c3e3830f21a69ea1fd4a09e"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-1304",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "e2fsprogs: out-of-bounds read/write via crafted filesystem",
        "Description": "An out-of-bounds read/write vulnerability was found in e2fsprogs 1.46.5. This issue leads to a segmentation fault and possibly arbitrary code execution via a specially crafted filesystem.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-125",
          "CWE-787"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
            "V2Score": 6.8,
            "V3Score": 7.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:L/I:L/A:H",
            "V3Score": 5.8
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2022:8361",
          "https://access.redhat.com/security/cve/CVE-2022-1304",
          "https://bugzilla.redhat.com/2069726",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2069726",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2083621",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-1304",
          "https://errata.almalinux.org/9/ALSA-2022-8361.html",
          "https://errata.rockylinux.org/RLSA-2022:7720",
          "https://linux.oracle.com/cve/CVE-2022-1304.html",
          "https://linux.oracle.com/errata/ELSA-2022-8361.html",
          "https://marc.info/?l=linux-ext4&m=165056234501732&w=2",
          "https://nvd.nist.gov/vuln/detail/CVE-2022-1304",
          "https://ubuntu.com/security/notices/USN-5464-1",
          "https://www.cve.org/CVERecord?id=CVE-2022-1304"
        ],
        "PublishedDate": "2022-04-14T21:15:00Z",
        "LastModifiedDate": "2023-02-12T22:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2019-8457",
        "PkgID": "libdb5.3@5.3.28+dfsg1-0.8",
        "PkgName": "libdb5.3",
        "InstalledVersion": "5.3.28+dfsg1-0.8",
        "Layer": {
          "DiffID": "sha256:cf9c7c9c9ad7d79832b60d51276862448b70fc11a3f9ecd2c4418c435132537b"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-8457",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "sqlite: heap out-of-bound read in function rtreenode()",
        "Description": "SQLite3 from 3.6.0 to and including 3.27.2 is vulnerable to heap out-of-bound read in the rtreenode() function when handling invalid rtree tables.",
        "Severity": "CRITICAL",
        "CweIDs": [
          "CWE-125"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V2Score": 7.5,
            "V3Score": 9.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          }
        },
        "References": [
          "http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00074.html",
          "https://access.redhat.com/security/cve/CVE-2019-8457",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-8457",
          "https://kc.mcafee.com/corporate/index?page=content&id=SB10365",
          "https://linux.oracle.com/cve/CVE-2019-8457.html",
          "https://linux.oracle.com/errata/ELSA-2020-1810.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OPKYSWCOM3CL66RI76TYVIG6TJ263RXH/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SJPFGA45DI4F5MCF2OAACGH3HQOF4G3M/",
          "https://nvd.nist.gov/vuln/detail/CVE-2019-8457",
          "https://security.netapp.com/advisory/ntap-20190606-0002/",
          "https://ubuntu.com/security/notices/USN-4004-1",
          "https://ubuntu.com/security/notices/USN-4004-2",
          "https://ubuntu.com/security/notices/USN-4019-1",
          "https://ubuntu.com/security/notices/USN-4019-2",
          "https://usn.ubuntu.com/4004-1/",
          "https://usn.ubuntu.com/4004-2/",
          "https://usn.ubuntu.com/4019-1/",
          "https://usn.ubuntu.com/4019-2/",
          "https://www.cve.org/CVERecord?id=CVE-2019-8457",
          "https://www.oracle.com/security-alerts/cpuapr2020.html",
          "https://www.oracle.com/security-alerts/cpujan2020.html",
          "https://www.oracle.com/security-alerts/cpujul2020.html",
          "https://www.oracle.com/technetwork/security-advisory/cpuoct2019-5072832.html",
          "https://www.sqlite.org/releaselog/3_28_0.html",
          "https://www.sqlite.org/src/info/90acdbfce9c08858"
        ],
        "PublishedDate": "2019-05-30T16:29:00Z",
        "LastModifiedDate": "2021-07-31T08:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2023-29491",
        "PkgID": "libncursesw6@6.2+20201114-2+deb11u1",
        "PkgName": "libncursesw6",
        "InstalledVersion": "6.2+20201114-2+deb11u1",
        "Layer": {
          "DiffID": "sha256:fd288e5dc11107870eac2899f7bd3777556835c371411d5bfb2eea2572a7cbf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-29491",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "Local users can trigger security-relevant memory corruption via malformed data",
        "Description": "ncurses before 6.4 20230408, when used by a setuid application, allows local users to trigger security-relevant memory corruption via malformed data in a terminfo database file that is found in $HOME/.terminfo or reached via the TERMINFO or TERM environment variable.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-787"
        ],
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 7.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 7.8
          }
        },
        "References": [
          "http://ncurses.scripts.mit.edu/?p=ncurses.git;a=commit;h=eb51b1ea1f75a0ec17c9c5937cb28df1e8eeec56",
          "http://www.openwall.com/lists/oss-security/2023/04/19/10",
          "http://www.openwall.com/lists/oss-security/2023/04/19/11",
          "https://access.redhat.com/security/cve/CVE-2023-29491",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-29491",
          "https://invisible-island.net/ncurses/NEWS.html#index-t20230408",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-29491",
          "https://security.netapp.com/advisory/ntap-20230517-0009/",
          "https://ubuntu.com/security/notices/USN-6099-1",
          "https://www.cve.org/CVERecord?id=CVE-2023-29491",
          "https://www.openwall.com/lists/oss-security/2023/04/12/5",
          "https://www.openwall.com/lists/oss-security/2023/04/13/4"
        ],
        "PublishedDate": "2023-04-14T01:15:00Z",
        "LastModifiedDate": "2023-05-17T20:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-29921",
        "PkgID": "libpython3.9-minimal@3.9.2-1",
        "PkgName": "libpython3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:2b66cde7d0cfbda919a0c334aa0e96e1f702a1dde1656f1075ce3d50aab562d9"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-29921",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python-ipaddress: Improper input validation of octal strings",
        "Description": "In Python before 3,9,5, the ipaddress library mishandles leading zero characters in the octets of an IP address string. This (in some situations) allows attackers to bypass access control that is based on IP addresses.",
        "Severity": "CRITICAL",
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V2Score": 7.5,
            "V3Score": 9.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
            "V3Score": 9.1
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2021-29921",
          "https://bugs.python.org/issue36384",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-29921",
          "https://docs.python.org/3/library/ipaddress.html",
          "https://errata.almalinux.org/8/ALSA-2021-4162.html",
          "https://github.com/python/cpython/blob/63298930fb531ba2bb4f23bc3b915dbf1e17e9e1/Misc/NEWS.d/3.8.0a4.rst",
          "https://github.com/python/cpython/pull/12577",
          "https://github.com/python/cpython/pull/25099",
          "https://github.com/sickcodes",
          "https://github.com/sickcodes/security/blob/master/advisories/SICK-2021-014.md",
          "https://linux.oracle.com/cve/CVE-2021-29921.html",
          "https://linux.oracle.com/errata/ELSA-2021-4162.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-29921",
          "https://python-security.readthedocs.io/vuln/ipaddress-ipv4-leading-zeros.html",
          "https://security.gentoo.org/glsa/202305-02",
          "https://security.netapp.com/advisory/ntap-20210622-0003/",
          "https://sick.codes/sick-2021-014",
          "https://ubuntu.com/security/notices/USN-4973-1",
          "https://ubuntu.com/security/notices/USN-4973-2",
          "https://www.cve.org/CVERecord?id=CVE-2021-29921",
          "https://www.oracle.com//security-alerts/cpujul2021.html",
          "https://www.oracle.com/security-alerts/cpuapr2022.html",
          "https://www.oracle.com/security-alerts/cpujan2022.html",
          "https://www.oracle.com/security-alerts/cpujul2022.html",
          "https://www.oracle.com/security-alerts/cpuoct2021.html"
        ],
        "PublishedDate": "2021-05-06T13:15:00Z",
        "LastModifiedDate": "2023-05-03T11:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2015-20107",
        "PkgID": "libpython3.9-minimal@3.9.2-1",
        "PkgName": "libpython3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:2b66cde7d0cfbda919a0c334aa0e96e1f702a1dde1656f1075ce3d50aab562d9"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2015-20107",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: mailcap: findmatch() function does not sanitize the second argument",
        "Description": "In Python (aka CPython) up to 3.10.8, the mailcap module does not add escape characters into commands discovered in the system mailcap file. This may allow attackers to inject shell commands into applications that call mailcap.findmatch with untrusted input (if they lack validation of user-provided filenames or arguments). The fix is also back-ported to 3.7, 3.8, 3.9",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-77"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:S/C:P/I:C/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:H/A:L",
            "V2Score": 8,
            "V3Score": 7.6
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:H/A:L",
            "V3Score": 7.6
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2022:8353",
          "https://access.redhat.com/security/cve/CVE-2015-20107",
          "https://bugs.python.org/issue24778",
          "https://bugzilla.redhat.com/2075390",
          "https://bugzilla.redhat.com/2120642",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2054702",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2059951",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2075390",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2120642",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2128249",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-20107",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-28861",
          "https://errata.almalinux.org/9/ALSA-2022-8353.html",
          "https://errata.rockylinux.org/RLSA-2022:8353",
          "https://github.com/python/cpython/issues/68966",
          "https://github.com/python/cpython/pull/91542/commits/340251550897cb98ae83ad1040750d6300112e80",
          "https://github.com/python/cpython/pull/91993",
          "https://linux.oracle.com/cve/CVE-2015-20107.html",
          "https://linux.oracle.com/errata/ELSA-2022-8353.html",
          "https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/46KWPTI72SSEOF53DOYQBQOCN4QQB2GE/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/53TQZFLS6O3FLIMVSXFEEPZSWLDZLBOX/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/57NECACX333A3BBZM2TR2VZ4ZE3UG3SN/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5DBVY4YC2P6EPZZ2DROOXHDOWZ4BJFLW/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6QIKVSW3H6W2GQGDE5DTIWLGFNH6KKEW/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AKGMYDVKI3XNM27B6I6RQ6QV3TVJAUCG/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ERYMM2QVDPOJLX4LYXWYIQN5FOIJLDRY/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/F3LNY2NHM6J22O6Q5ANOE3SZRK3OACKR/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FCIO2W4DUVVMI6L52QCC4TT2B3K5VWHS/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FIRUTX47BJD2HYJDLMI7JJBVCYFAPKAQ/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GPCLGZZJPVXFWUWVV5WCD5FNUAFLKBDN/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HAI2GBC7WKH7J5NH6J2IW5RT3VF2SF5M/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IFGV7P2PYFBMK32OKHCAC2ZPJQV5AUDF/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KAY6VBNVEFUXKJF37WFHYXUSRDEK34N3/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MYG3EMFR7ZHC46TDNM7SNWO64A3W7EUF/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ONXSGLASNLGFL57YU6WT6Y5YURSFV43U/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PTTZGLD2YBMMG6U6F5HOTPOGGPBIURMA/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UIOJUZ5JMEMGSKNISTOVI4PDP36FDL5Y/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/W5664BGZVTA46LQDNTYX5THG6CN4FYJX/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WXF6MQ74HVIDDSR5AE2UDR24I6D4FEPC/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XO2H6CKWLRGTTZCGUQVELW6LUH437Q3O/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/Y4E2WBEJ42CGLGDHD6ZXOLZ2W6G3YOVD/",
          "https://mail.python.org/archives/list/security-announce@python.org/thread/QDSXNCW77UGULFG2JMDFZQ7H4DIR32LA/",
          "https://nvd.nist.gov/vuln/detail/CVE-2015-20107",
          "https://python-security.readthedocs.io/vuln/mailcap-shell-injection.html",
          "https://security.gentoo.org/glsa/202305-02",
          "https://security.netapp.com/advisory/ntap-20220616-0001/",
          "https://ubuntu.com/security/notices/USN-5519-1",
          "https://ubuntu.com/security/notices/USN-5888-1",
          "https://www.cve.org/CVERecord?id=CVE-2015-20107"
        ],
        "PublishedDate": "2022-04-13T16:15:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2020-10735",
        "PkgID": "libpython3.9-minimal@3.9.2-1",
        "PkgName": "libpython3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:2b66cde7d0cfbda919a0c334aa0e96e1f702a1dde1656f1075ce3d50aab562d9"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-10735",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "int() type in PyLong_FromString() does not limit amount of digits converting text to int leading to DoS",
        "Description": "A flaw was found in python. In algorithms with quadratic time complexity using non-binary bases, when using int(\"text\"), a system could take 50ms to parse an int string with 100,000 digits and 5s for 1,000,000 digits (float, decimal, int.from_bytes(), and int() for binary bases 2, 4, 8, 16, and 32 are not affected). The highest threat from this vulnerability is to system availability.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-704"
        ],
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          }
        },
        "References": [
          "http://www.openwall.com/lists/oss-security/2022/09/21/1",
          "http://www.openwall.com/lists/oss-security/2022/09/21/4",
          "https://access.redhat.com/errata/RHSA-2022:7323",
          "https://access.redhat.com/security/cve/CVE-2020-10735",
          "https://bugzilla.redhat.com/1834423",
          "https://bugzilla.redhat.com/show_bug.cgi?id=1834423",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2120642",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2144072",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-10735",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-28861",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-45061",
          "https://docs.google.com/document/d/1KjuF_aXlzPUxTK4BMgezGJ2Pn7uevfX7g0_mvgHlL7Y",
          "https://errata.almalinux.org/9/ALSA-2022-7323.html",
          "https://errata.rockylinux.org/RLSA-2023:0833",
          "https://github.com/python/cpython/issues/95778",
          "https://linux.oracle.com/cve/CVE-2020-10735.html",
          "https://linux.oracle.com/errata/ELSA-2023-2764.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/2VCU6EVQDIXNCEDJUCTFIER2WVNNDTYZ/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/32AAQKABEKFCB5DDV5OONRZK6BS23HPW/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4EWKR2SPX3JORLWCXFY3KN2U5B5CIUQQ/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6XL6E5A3I36TRR73VNBOXNIQP4AMZDFZ/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/76YE7AM37MRU76XJV4M27CWDAMUGNRYK/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HSRPVJZL6DJFWKYRHMNJB7VCEUCBKRF5/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/IFGV7P2PYFBMK32OKHCAC2ZPJQV5AUDF/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NHC6IUU7CLRQ3QLPWUXLONSG3SXFTR47/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OKYE2DOI2X7WZXAWTQJZAXYIWM37HDCY/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OT5U223OE5ZOUHZAZYSYSWVJQIKDE73E/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OT5WQB7Z3CXOWVBD2AFAHYPA5ONYFFZ4/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PD7FTLJOIGMUSCDR3JAN6WRFHJEE4PH5/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SZYJSGLSCQOKXXFVJVJQAXLEOJBIWGEL/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/TD7JDDKJXK6D26XAN3YRFNM2LAJHT5UO/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/TMWPRAAJS7I6U3U45V7GZVXWNSECI22M/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/U4ZZV4CDFRMTPDBI7C5L43RFL3XLIGUY/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/UBPDVCDIUCEBE7C4NAGNA2KQJYOTPBAZ/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/V7ZUJDHK7KNG6SLIFXW7MNZ6O2PUJYK6/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/WXF6MQ74HVIDDSR5AE2UDR24I6D4FEPC/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ZEOAJWGGY55QU35UM2OVZATBW5MX2OZD/",
          "https://nvd.nist.gov/vuln/detail/CVE-2020-10735",
          "https://www.cve.org/CVERecord?id=CVE-2020-10735"
        ],
        "PublishedDate": "2022-09-09T14:15:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-3737",
        "PkgID": "libpython3.9-minimal@3.9.2-1",
        "PkgName": "libpython3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:2b66cde7d0cfbda919a0c334aa0e96e1f702a1dde1656f1075ce3d50aab562d9"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-3737",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "HTTP client possible infinite loop on a 100 Continue response",
        "Description": "A flaw was found in python. An improperly handled HTTP response in the HTTP client code of python may allow a remote attacker, who controls the HTTP server, to make the client script enter an infinite loop, consuming CPU time. The highest threat from this vulnerability is to system availability.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-400",
          "CWE-835"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:M/Au:N/C:N/I:N/A:C",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V2Score": 7.1,
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 6.5
          }
        },
        "References": [
          "https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-3737.json",
          "https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-4189.json",
          "https://access.redhat.com/security/cve/CVE-2021-3737",
          "https://bugs.python.org/issue44022",
          "https://bugzilla.redhat.com/show_bug.cgi?id=1995162",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3737",
          "https://errata.almalinux.org/8/ALSA-2022-1986.html",
          "https://github.com/python/cpython/commit/0389426fa4af4dfc8b1d7f3f291932d928392d8b (3.8 branch)",
          "https://github.com/python/cpython/commit/078b146f062d212919d0ba25e34e658a8234aa63 (v3.7.11)",
          "https://github.com/python/cpython/commit/1b6f4e5e13ebd1f957b47f7415b53d0869bdbac6 (v3.6.14",
          "https://github.com/python/cpython/commit/5df4abd6b033a5f1e48945c6988b45e35e76f647 (v3.9.6)",
          "https://github.com/python/cpython/commit/60ba0b68470a584103e28958d91e93a6db37ec92 (v3.10.0b2)",
          "https://github.com/python/cpython/commit/98e5a7975d99b58d511f171816ecdfb13d5cca18 (v3.10.0b3)",
          "https://github.com/python/cpython/commit/ea9327036680acc92d9f89eaf6f6a54d2f8d78d9 (v3.9.6)",
          "https://github.com/python/cpython/commit/f396864ddfe914531b5856d7bf852808ebfc01ae (v3.8.11)",
          "https://github.com/python/cpython/commit/f68d2d69f1da56c2aea1293ecf93ab69a6010ad7 (v3.6.14)",
          "https://github.com/python/cpython/commit/fee96422e6f0056561cf74fef2012cc066c9db86 (v3.7.11)",
          "https://github.com/python/cpython/pull/25916",
          "https://github.com/python/cpython/pull/26503",
          "https://linux.oracle.com/cve/CVE-2021-3737.html",
          "https://linux.oracle.com/errata/ELSA-2022-1986.html",
          "https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-3737",
          "https://python-security.readthedocs.io/vuln/urllib-100-continue-loop.html",
          "https://security.netapp.com/advisory/ntap-20220407-0009/",
          "https://ubuntu.com/security/CVE-2021-3737",
          "https://ubuntu.com/security/notices/USN-5083-1",
          "https://ubuntu.com/security/notices/USN-5199-1",
          "https://ubuntu.com/security/notices/USN-5200-1",
          "https://ubuntu.com/security/notices/USN-5201-1",
          "https://www.cve.org/CVERecord?id=CVE-2021-3737",
          "https://www.oracle.com/security-alerts/cpujul2022.html"
        ],
        "PublishedDate": "2022-03-04T19:15:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2022-0391",
        "PkgID": "libpython3.9-minimal@3.9.2-1",
        "PkgName": "libpython3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:2b66cde7d0cfbda919a0c334aa0e96e1f702a1dde1656f1075ce3d50aab562d9"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-0391",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: urllib.parse does not sanitize URLs containing ASCII newline and tabs",
        "Description": "A flaw was found in Python, specifically within the urllib.parse module. This module helps break Uniform Resource Locator (URL) strings into components. The issue involves how the urlparse method does not sanitize input and allows characters like '\\r' and '\\n' in the URL path. This flaw allows an attacker to input a crafted URL, leading to injection attacks. This flaw affects Python versions prior to 3.10.0b1, 3.9.5, 3.8.11, 3.7.11 and 3.6.14.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-74"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:N/I:P/A:N",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V2Score": 5,
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "V3Score": 5.3
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2022:6457",
          "https://access.redhat.com/security/cve/CVE-2022-0391",
          "https://bugs.python.org/issue43882",
          "https://bugzilla.redhat.com/2047376",
          "https://bugzilla.redhat.com/2075390",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-0391",
          "https://errata.almalinux.org/8/ALSA-2022-6457.html",
          "https://linux.oracle.com/cve/CVE-2022-0391.html",
          "https://linux.oracle.com/errata/ELSA-2023-3550.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CSD2YBXP3ZF44E44QMIIAR5VTO35KTRB/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UDBDBAU6HUPZHISBOARTXZ5GKHF2VH5U/",
          "https://nvd.nist.gov/vuln/detail/CVE-2022-0391",
          "https://security.gentoo.org/glsa/202305-02",
          "https://security.netapp.com/advisory/ntap-20220225-0009/",
          "https://ubuntu.com/security/notices/USN-5342-1",
          "https://ubuntu.com/security/notices/USN-5342-2",
          "https://www.cve.org/CVERecord?id=CVE-2022-0391",
          "https://www.oracle.com/security-alerts/cpuapr2022.html"
        ],
        "PublishedDate": "2022-02-09T23:15:00Z",
        "LastModifiedDate": "2023-05-03T11:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2022-42919",
        "PkgID": "libpython3.9-minimal@3.9.2-1",
        "PkgName": "libpython3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:2b66cde7d0cfbda919a0c334aa0e96e1f702a1dde1656f1075ce3d50aab562d9"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-42919",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "local privilege escalation via the multiprocessing forkserver start method",
        "Description": "Python 3.9.x before 3.9.16 and 3.10.x before 3.10.9 on Linux allows local privilege escalation in a non-default configuration. The Python multiprocessing library, when used with the forkserver start method on Linux, allows pickles to be deserialized from any user in the same machine local network namespace, which in many system configurations means any user on the same machine. Pickles can execute arbitrary code. Thus, this allows for local user privilege escalation to the user that any forkserver process is running as. Setting multiprocessing.util.abstract_sockets_supported to False is a workaround. The forkserver start method for multiprocessing is not the default start method. This issue is Linux specific because only Linux supports abstract namespace sockets. CPython before 3.9 does not make use of Linux abstract namespace sockets by default. Support for users manually specifying an abstract namespace socket was added as a bugfix in 3.7.8 and 3.8.3, but users would need to make specific uncommon API calls in order to do that in CPython before 3.9.",
        "Severity": "HIGH",
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 7.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 7.8
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2022:8493",
          "https://access.redhat.com/security/cve/CVE-2022-42919",
          "https://bugzilla.redhat.com/2138705",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2138705",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-42919",
          "https://errata.almalinux.org/9/ALSA-2022-8493.html",
          "https://errata.rockylinux.org/RLSA-2022:8493",
          "https://github.com/python/cpython/compare/v3.10.8...v3.10.9",
          "https://github.com/python/cpython/compare/v3.9.15...v3.9.16",
          "https://github.com/python/cpython/issues/97514",
          "https://github.com/python/cpython/issues/97514#issuecomment-1310277840",
          "https://linux.oracle.com/cve/CVE-2022-42919.html",
          "https://linux.oracle.com/errata/ELSA-2022-8493.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FKGCQPIVHEAIJ77R3RSNSQWYBUDVWDKU/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/P2LHWWEI5OBQ6RELULMVU6KMDYG4WZXH/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PI5DYIED6U26BGX5IRZWNCP6TY4M2ZGZ/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QLUGZSEAO3MBWGKCUSMKQIRYJZKJCIOB/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/R6KGIRHSENZ4QAB234Z36HVIDTRJ3MFI/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RDK3ZZBRYFO47ET3N4BNTKVXN47U6ICY/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VCRKBB5Y5EWTJUNC7LK665WO64DDXSTN/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XX6LLAXGZVZ327REY6MDZRMMP47LJ53P/",
          "https://nvd.nist.gov/vuln/detail/CVE-2022-42919",
          "https://python-security.readthedocs.io/vuln/multiprocessing-abstract-socket.html",
          "https://security.gentoo.org/glsa/202305-02",
          "https://security.netapp.com/advisory/ntap-20221209-0006/",
          "https://ubuntu.com/security/notices/USN-5713-1",
          "https://ubuntu.com/security/notices/USN-5888-1",
          "https://www.cve.org/CVERecord?id=CVE-2022-42919"
        ],
        "PublishedDate": "2022-11-07T00:15:00Z",
        "LastModifiedDate": "2023-05-03T11:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2022-45061",
        "PkgID": "libpython3.9-minimal@3.9.2-1",
        "PkgName": "libpython3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:2b66cde7d0cfbda919a0c334aa0e96e1f702a1dde1656f1075ce3d50aab562d9"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-45061",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "CPU denial of service via inefficient IDNA decoder",
        "Description": "An issue was discovered in Python before 3.11.1. An unnecessary quadratic algorithm exists in one path when processing some inputs to the IDNA (RFC 3490) decoder, such that a crafted, unreasonably long name being presented to the decoder could lead to a CPU denial of service. Hostnames are often supplied by remote servers that could be controlled by a malicious actor; in such a scenario, they could trigger excessive CPU consumption on the client attempting to make use of an attacker-supplied supposed hostname. For example, the attack payload could be placed in the Location header of an HTTP response with status code 302. A fix is planned in 3.11.1, 3.10.9, 3.9.16, 3.8.16, and 3.7.16.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-400"
        ],
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2023:0953",
          "https://access.redhat.com/security/cve/CVE-2022-45061",
          "https://bugzilla.redhat.com/2144072",
          "https://bugzilla.redhat.com/show_bug.cgi?id=1834423",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2120642",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2144072",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-10735",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-28861",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-45061",
          "https://errata.almalinux.org/9/ALSA-2023-0953.html",
          "https://errata.rockylinux.org/RLSA-2023:0833",
          "https://github.com/python/cpython/issues/98433",
          "https://github.com/python/cpython/pull/99092",
          "https://github.com/python/cpython/pull/99230 (3.9-branch)",
          "https://github.com/python/cpython/pull/99231 (3.8-branch)",
          "https://linux.oracle.com/cve/CVE-2022-45061.html",
          "https://linux.oracle.com/errata/ELSA-2023-2860.html",
          "https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2AOUKI72ACV6CHY2QUFO6VK2DNMVJ2MB/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/35YDIWCUMWTMDBWFRAVENFH6BLB65D6S/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4WBZJNSALFGMPYTINIF57HAAK46U72WQ/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/63FS6VHY4DCS74HBTEINUDOECQ2X6ZCH/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7WQPHKGNXUJC3TC3BDW5RKGROWRJVSFR/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B3YI6JYARWU6GULWOHNUROSACT54XFFS/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GTPVDZDATRQFE6KAT6B4BQIQ4GRHIIIJ/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IN26PWZTYG6IF3APLRXQJBVACQHZUPT2/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JCDJXNBHWXNYUTOEV4H2HCFSRKV3SYL3/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JTYVESWVBPD57ZJC35G5722Q6TS37WSB/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KNE4GMD45RGC2HWUAAIGTDHT5VJ2E4O4/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LKWAMPURWUV3DCCT4J7VHRF4NT2CFVBR/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O67LRHDTJWH544KXB6KY4HMHQLYDXFPK/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ORVCQGJCCAVLN4DJDTWGREFCUWXKQRML/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PLQ2BNZVBBAQPV3SPRU24ZD37UYJJS7W/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QLUGZSEAO3MBWGKCUSMKQIRYJZKJCIOB/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RDK3ZZBRYFO47ET3N4BNTKVXN47U6ICY/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RH57BNT4VQERGEJ5SXNXSVMDYP66YD4H/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RTN2OOLKYTG34DODUEJGT5MLC2PFGPBA/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T3D5TX4TDJPXHXD2QICKTY3OCQC3JARP/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UHVW73QZJMHA4MK7JBT7CXX7XSNYQEGF/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VCMDX6IFKLOA3NXUQEV524L5LHTPI2JI/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/X3EJ6J7PXVQOULBQZQGBXCXY6LFF6LZD/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XXZJL3CNAFS5PAIR7K4RL62S3Y7THR7O/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YPNWZKXPKTNHS5FVMN7UQZ2UPCSEFJUK/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZB5YCMIRVX35RUB6XPOWKENCVCJEVDRK/",
          "https://nvd.nist.gov/vuln/detail/CVE-2022-45061",
          "https://python-security.readthedocs.io/vuln/slow-idna-large-strings.html",
          "https://security.gentoo.org/glsa/202305-02",
          "https://security.netapp.com/advisory/ntap-20221209-0007/",
          "https://ubuntu.com/security/notices/USN-5767-1",
          "https://ubuntu.com/security/notices/USN-5767-2",
          "https://ubuntu.com/security/notices/USN-5888-1",
          "https://www.cve.org/CVERecord?id=CVE-2022-45061"
        ],
        "PublishedDate": "2022-11-09T07:15:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2023-24329",
        "PkgID": "libpython3.9-minimal@3.9.2-1",
        "PkgName": "libpython3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:2b66cde7d0cfbda919a0c334aa0e96e1f702a1dde1656f1075ce3d50aab562d9"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-24329",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "urllib.parse url blocklisting bypass",
        "Description": "An issue in the urllib.parse component of Python before 3.11.4 allows attackers to bypass blocklisting methods by supplying a URL that starts with blank characters.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-20"
        ],
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2023:3595",
          "https://access.redhat.com/security/cve/CVE-2023-24329",
          "https://bugzilla.redhat.com/2173917",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2173917",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-24329",
          "https://errata.almalinux.org/9/ALSA-2023-3595.html",
          "https://errata.rockylinux.org/RLSA-2023:3591",
          "https://github.com/python/cpython/issues/102153",
          "https://github.com/python/cpython/pull/99421",
          "https://github.com/python/cpython/pull/99446 (backport for 3.11 branch)",
          "https://linux.oracle.com/cve/CVE-2023-24329.html",
          "https://linux.oracle.com/errata/ELSA-2023-3595.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6PEVICI7YNGGMSL3UCMWGE66QFLATH72/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DSL6NSOAXWBJJ67XPLSSC74MNKZF3BBO/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/EM2XLZSTXG44TMFXF4E6VTGKR2MQCW3G/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/F2NY75GFDZ5T6YPN44D3VMFT5SUVTOTG/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GR5US3BYILYJ4SKBV6YBNPRUBAL5P2CN/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/H23OSKC6UG6IWOQAUPW74YUHWRWVXJP7/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JZTLGV2HYFF4AMYJL25VDIGAIHCU7UPA/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LWC4WGXER5P6Q75RFGL7QUTPP3N5JR7T/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MZEHSXSCMA4WWQKXT6QV7AAR6SWNZ2VP/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O5SP4RT3RRS434ZS2HQKQJ3VZW7YPKYR/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OHHJHJRLEF3TDT2K3676CAUVRDD4CCMR/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PEUN6T22UJFXR7J5F6UUHCXXPKJ2DVHI/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PURM5CFDABEWAIWZFD2MQ7ZJGCPYSQ44/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/Q3J5N24ECS4B6MJDRO6UAYU6GPLYBDCL/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QRQHN7RWJQJHYP6E5EKESOYP5VDSHZG4/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RA2MBEEES6L46OD64OBSVUUMGKNGMOWW/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T4IDB5OAR5Y4UK3HLMZBW4WEL2B7YFMJ/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TZH26JGNZ5XYPZ5SAU3NKSBSPRE5OHTG/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/U2MZOJYGFCB5PPT6AKMAU72N7QOYWLBP/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UONZWLB4QVLQIY5CPDLEUEKH6WX4VQMC/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WTOAUJNDWZDRWVSXJ354AYZYKRMT56HU/",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-24329",
          "https://pointernull.com/security/python-url-parse-problem.html",
          "https://security.netapp.com/advisory/ntap-20230324-0004/",
          "https://ubuntu.com/security/notices/USN-5888-1",
          "https://ubuntu.com/security/notices/USN-5960-1",
          "https://ubuntu.com/security/notices/USN-6139-1",
          "https://www.cve.org/CVERecord?id=CVE-2023-24329"
        ],
        "PublishedDate": "2023-02-17T15:15:00Z",
        "LastModifiedDate": "2023-06-16T04:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-3426",
        "PkgID": "libpython3.9-minimal@3.9.2-1",
        "PkgName": "libpython3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:2b66cde7d0cfbda919a0c334aa0e96e1f702a1dde1656f1075ce3d50aab562d9"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-3426",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: Information disclosure via pydoc",
        "Description": "There's a flaw in Python 3's pydoc. A local or adjacent attacker who discovers or is able to convince another local or adjacent user to start a pydoc server could access the server and use it to disclose sensitive information belonging to the other user that they would not normally be able to access. The highest risk of this flaw is to data confidentiality. This flaw affects Python versions before 3.8.9, Python versions before 3.9.3 and Python versions before 3.10.0a7.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-22"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:A/AC:L/Au:S/C:P/I:N/A:N",
            "V3Vector": "CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
            "V2Score": 2.7,
            "V3Score": 5.7
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
            "V3Score": 5.7
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2021-3426",
          "https://bugzilla.redhat.com/show_bug.cgi?id=1935913",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3426",
          "https://github.com/python/cpython/pull/24285",
          "https://github.com/python/cpython/pull/24337",
          "https://linux.oracle.com/cve/CVE-2021-3426.html",
          "https://linux.oracle.com/errata/ELSA-2021-9562.html",
          "https://lists.debian.org/debian-lts-announce/2021/04/msg00005.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/25HVHLBGO2KNPXJ3G426QEYSSCECJDU5/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BF2K7HEWADHN6P52R3QLIOX27U3DJ4HI/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DQYPUKLLBOZMKFPO7RD7CENTXHUUEUV7/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LM5V4VPLBHBEASSAROYPSHXGXGGPHNOE/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N6VXJZSZ6N64AILJX4CTMACYGQGHHD5C/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QNGAFMPIYIVJ47FCF2NK2PIX22HUG35B/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VPX7Y5GQDNB4FJTREWONGC4ZSVH7TGHF/",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-3426",
          "https://python-security.readthedocs.io/vuln/pydoc-getfile.html",
          "https://security.gentoo.org/glsa/202104-04",
          "https://security.netapp.com/advisory/ntap-20210629-0003/",
          "https://ubuntu.com/security/notices/USN-5342-1",
          "https://ubuntu.com/security/notices/USN-5342-3",
          "https://www.cve.org/CVERecord?id=CVE-2021-3426",
          "https://www.oracle.com/security-alerts/cpujan2022.html",
          "https://www.oracle.com/security-alerts/cpuoct2021.html"
        ],
        "PublishedDate": "2021-05-20T13:15:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-3733",
        "PkgID": "libpython3.9-minimal@3.9.2-1",
        "PkgName": "libpython3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:2b66cde7d0cfbda919a0c334aa0e96e1f702a1dde1656f1075ce3d50aab562d9"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-3733",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: urllib: Regular expression DoS in AbstractBasicAuthHandler",
        "Description": "There's a flaw in urllib's AbstractBasicAuthHandler class. An attacker who controls a malicious HTTP server that an HTTP client (such as web browser) connects to, could trigger a Regular Expression Denial of Service (ReDOS) during an authentication request with a specially crafted payload that is sent by the server to the client. The greatest threat that this flaw poses is to application availability.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-400"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:S/C:N/I:N/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
            "V2Score": 4,
            "V3Score": 6.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 6.5
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2021-3733",
          "https://bugs.python.org/issue43075",
          "https://bugzilla.redhat.com/show_bug.cgi?id=1995234",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3733",
          "https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-14-final",
          "https://docs.python.org/3.7/whatsnew/changelog.html#python-3-7-11-final",
          "https://docs.python.org/3.8/whatsnew/changelog.html#python-3-8-10-final",
          "https://docs.python.org/3.9/whatsnew/changelog.html#python-3-9-5-final",
          "https://errata.almalinux.org/8/ALSA-2022-1821.html",
          "https://github.com/python/cpython/commit/3fbe96123aeb66664fa547a8f6022efa2dc8788f (3.6.14)",
          "https://github.com/python/cpython/commit/7215d1ae25525c92b026166f9d5cac85fb",
          "https://github.com/python/cpython/commit/7215d1ae25525c92b026166f9d5cac85fb1defe1 (master)",
          "https://github.com/python/cpython/commit/a21d4fbd549ec9685068a113660553d7f80d9b09 (3.9.5)",
          "https://github.com/python/cpython/commit/ada14995870abddc277addf57dd690a2af04c2da (3.7.11)",
          "https://github.com/python/cpython/commit/e7654b6046090914a8323931ed759a94a5f85d60 (3.8.10)",
          "https://github.com/python/cpython/pull/24391",
          "https://linux.oracle.com/cve/CVE-2021-3733.html",
          "https://linux.oracle.com/errata/ELSA-2022-1821.html",
          "https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-3733",
          "https://security.netapp.com/advisory/ntap-20220407-0001/",
          "https://ubuntu.com/security/CVE-2021-3733",
          "https://ubuntu.com/security/notices/USN-5083-1",
          "https://ubuntu.com/security/notices/USN-5199-1",
          "https://ubuntu.com/security/notices/USN-5200-1",
          "https://www.cve.org/CVERecord?id=CVE-2021-3733"
        ],
        "PublishedDate": "2022-03-10T17:42:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-4189",
        "PkgID": "libpython3.9-minimal@3.9.2-1",
        "PkgName": "libpython3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:2b66cde7d0cfbda919a0c334aa0e96e1f702a1dde1656f1075ce3d50aab562d9"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-4189",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "ftplib should not use the host from the PASV response",
        "Description": "A flaw was found in Python, specifically in the FTP (File Transfer Protocol) client library in PASV (passive) mode. The issue is how the FTP client trusts the host from the PASV response by default. This flaw allows an attacker to set up a malicious FTP server that can trick FTP clients into connecting back to a given IP address and port. This vulnerability could lead to FTP client scanning ports, which otherwise would not have been possible.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-252"
        ],
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "V3Score": 5.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "V3Score": 5.3
          }
        },
        "References": [
          "https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-3737.json",
          "https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-4189.json",
          "https://access.redhat.com/security/cve/CVE-2021-4189",
          "https://bugs.python.org/issue43285",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2036020",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-4189",
          "https://errata.almalinux.org/8/ALSA-2022-1986.html",
          "https://github.com/python/cpython/commit/0ab152c6b5d95caa2dc1a30fa96e10258b5f188e",
          "https://github.com/python/cpython/commit/0ab152c6b5d95caa2dc1a30fa96e10258b5f188e (master)",
          "https://github.com/python/cpython/commit/4134f154ae2f621f25c5d698cc0f1748035a1b88 (v3.6.14)",
          "https://github.com/python/cpython/commit/79373951b3eab585d42e0f0ab83718cbe1d0ee33 (v3.7.11)",
          "https://github.com/python/cpython/commit/7dcb4baa4f0fde3aef5122a8e9f6a41853ec9335 (v3.9.3)",
          "https://linux.oracle.com/cve/CVE-2021-4189.html",
          "https://linux.oracle.com/errata/ELSA-2022-1986.html",
          "https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-4189",
          "https://python-security.readthedocs.io/vuln/ftplib-pasv.html",
          "https://security-tracker.debian.org/tracker/CVE-2021-4189",
          "https://security.netapp.com/advisory/ntap-20221104-0004/",
          "https://ubuntu.com/security/notices/USN-5342-1",
          "https://ubuntu.com/security/notices/USN-5342-2",
          "https://www.cve.org/CVERecord?id=CVE-2021-4189"
        ],
        "PublishedDate": "2022-08-24T16:15:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2023-27043",
        "PkgID": "libpython3.9-minimal@3.9.2-1",
        "PkgName": "libpython3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:2b66cde7d0cfbda919a0c334aa0e96e1f702a1dde1656f1075ce3d50aab562d9"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-27043",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "Parsing errors in email/_parseaddr.py lead to incorrect value in email address part of tuple",
        "Description": "The email module of Python through 3.11.3 incorrectly parses e-mail addresses that contain a special character. The wrong portion of an RFC2822 header is identified as the value of the addr-spec. In some applications, an attacker can bypass a protection mechanism in which application access is granted only after verifying receipt of e-mail to a specific domain (e.g., only @company.example.com addresses may be used for signup). This occurs in email/_parseaddr.py in recent versions of Python.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-20"
        ],
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "V3Score": 5.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "V3Score": 5.3
          }
        },
        "References": [
          "http://python.org",
          "https://access.redhat.com/security/cve/CVE-2023-27043",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-27043",
          "https://github.com/python/cpython/issues/102988",
          "https://github.com/python/cpython/pull/102990",
          "https://github.com/python/cpython/pull/105127",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-27043",
          "https://python-security.readthedocs.io/vuln/email-parseaddr-realname.html",
          "https://security.netapp.com/advisory/ntap-20230601-0003/",
          "https://www.cve.org/CVERecord?id=CVE-2023-27043"
        ],
        "PublishedDate": "2023-04-19T00:15:00Z",
        "LastModifiedDate": "2023-06-01T14:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-29921",
        "PkgID": "libpython3.9-stdlib@3.9.2-1",
        "PkgName": "libpython3.9-stdlib",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e647281aeda207430048571c138604d8fcb88a8228cf3bab08e20602ff510002"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-29921",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python-ipaddress: Improper input validation of octal strings",
        "Description": "In Python before 3,9,5, the ipaddress library mishandles leading zero characters in the octets of an IP address string. This (in some situations) allows attackers to bypass access control that is based on IP addresses.",
        "Severity": "CRITICAL",
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V2Score": 7.5,
            "V3Score": 9.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
            "V3Score": 9.1
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2021-29921",
          "https://bugs.python.org/issue36384",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-29921",
          "https://docs.python.org/3/library/ipaddress.html",
          "https://errata.almalinux.org/8/ALSA-2021-4162.html",
          "https://github.com/python/cpython/blob/63298930fb531ba2bb4f23bc3b915dbf1e17e9e1/Misc/NEWS.d/3.8.0a4.rst",
          "https://github.com/python/cpython/pull/12577",
          "https://github.com/python/cpython/pull/25099",
          "https://github.com/sickcodes",
          "https://github.com/sickcodes/security/blob/master/advisories/SICK-2021-014.md",
          "https://linux.oracle.com/cve/CVE-2021-29921.html",
          "https://linux.oracle.com/errata/ELSA-2021-4162.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-29921",
          "https://python-security.readthedocs.io/vuln/ipaddress-ipv4-leading-zeros.html",
          "https://security.gentoo.org/glsa/202305-02",
          "https://security.netapp.com/advisory/ntap-20210622-0003/",
          "https://sick.codes/sick-2021-014",
          "https://ubuntu.com/security/notices/USN-4973-1",
          "https://ubuntu.com/security/notices/USN-4973-2",
          "https://www.cve.org/CVERecord?id=CVE-2021-29921",
          "https://www.oracle.com//security-alerts/cpujul2021.html",
          "https://www.oracle.com/security-alerts/cpuapr2022.html",
          "https://www.oracle.com/security-alerts/cpujan2022.html",
          "https://www.oracle.com/security-alerts/cpujul2022.html",
          "https://www.oracle.com/security-alerts/cpuoct2021.html"
        ],
        "PublishedDate": "2021-05-06T13:15:00Z",
        "LastModifiedDate": "2023-05-03T11:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2015-20107",
        "PkgID": "libpython3.9-stdlib@3.9.2-1",
        "PkgName": "libpython3.9-stdlib",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e647281aeda207430048571c138604d8fcb88a8228cf3bab08e20602ff510002"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2015-20107",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: mailcap: findmatch() function does not sanitize the second argument",
        "Description": "In Python (aka CPython) up to 3.10.8, the mailcap module does not add escape characters into commands discovered in the system mailcap file. This may allow attackers to inject shell commands into applications that call mailcap.findmatch with untrusted input (if they lack validation of user-provided filenames or arguments). The fix is also back-ported to 3.7, 3.8, 3.9",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-77"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:S/C:P/I:C/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:H/A:L",
            "V2Score": 8,
            "V3Score": 7.6
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:H/A:L",
            "V3Score": 7.6
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2022:8353",
          "https://access.redhat.com/security/cve/CVE-2015-20107",
          "https://bugs.python.org/issue24778",
          "https://bugzilla.redhat.com/2075390",
          "https://bugzilla.redhat.com/2120642",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2054702",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2059951",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2075390",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2120642",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2128249",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-20107",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-28861",
          "https://errata.almalinux.org/9/ALSA-2022-8353.html",
          "https://errata.rockylinux.org/RLSA-2022:8353",
          "https://github.com/python/cpython/issues/68966",
          "https://github.com/python/cpython/pull/91542/commits/340251550897cb98ae83ad1040750d6300112e80",
          "https://github.com/python/cpython/pull/91993",
          "https://linux.oracle.com/cve/CVE-2015-20107.html",
          "https://linux.oracle.com/errata/ELSA-2022-8353.html",
          "https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/46KWPTI72SSEOF53DOYQBQOCN4QQB2GE/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/53TQZFLS6O3FLIMVSXFEEPZSWLDZLBOX/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/57NECACX333A3BBZM2TR2VZ4ZE3UG3SN/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5DBVY4YC2P6EPZZ2DROOXHDOWZ4BJFLW/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6QIKVSW3H6W2GQGDE5DTIWLGFNH6KKEW/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AKGMYDVKI3XNM27B6I6RQ6QV3TVJAUCG/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ERYMM2QVDPOJLX4LYXWYIQN5FOIJLDRY/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/F3LNY2NHM6J22O6Q5ANOE3SZRK3OACKR/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FCIO2W4DUVVMI6L52QCC4TT2B3K5VWHS/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FIRUTX47BJD2HYJDLMI7JJBVCYFAPKAQ/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GPCLGZZJPVXFWUWVV5WCD5FNUAFLKBDN/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HAI2GBC7WKH7J5NH6J2IW5RT3VF2SF5M/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IFGV7P2PYFBMK32OKHCAC2ZPJQV5AUDF/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KAY6VBNVEFUXKJF37WFHYXUSRDEK34N3/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MYG3EMFR7ZHC46TDNM7SNWO64A3W7EUF/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ONXSGLASNLGFL57YU6WT6Y5YURSFV43U/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PTTZGLD2YBMMG6U6F5HOTPOGGPBIURMA/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UIOJUZ5JMEMGSKNISTOVI4PDP36FDL5Y/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/W5664BGZVTA46LQDNTYX5THG6CN4FYJX/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WXF6MQ74HVIDDSR5AE2UDR24I6D4FEPC/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XO2H6CKWLRGTTZCGUQVELW6LUH437Q3O/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/Y4E2WBEJ42CGLGDHD6ZXOLZ2W6G3YOVD/",
          "https://mail.python.org/archives/list/security-announce@python.org/thread/QDSXNCW77UGULFG2JMDFZQ7H4DIR32LA/",
          "https://nvd.nist.gov/vuln/detail/CVE-2015-20107",
          "https://python-security.readthedocs.io/vuln/mailcap-shell-injection.html",
          "https://security.gentoo.org/glsa/202305-02",
          "https://security.netapp.com/advisory/ntap-20220616-0001/",
          "https://ubuntu.com/security/notices/USN-5519-1",
          "https://ubuntu.com/security/notices/USN-5888-1",
          "https://www.cve.org/CVERecord?id=CVE-2015-20107"
        ],
        "PublishedDate": "2022-04-13T16:15:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2020-10735",
        "PkgID": "libpython3.9-stdlib@3.9.2-1",
        "PkgName": "libpython3.9-stdlib",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e647281aeda207430048571c138604d8fcb88a8228cf3bab08e20602ff510002"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-10735",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "int() type in PyLong_FromString() does not limit amount of digits converting text to int leading to DoS",
        "Description": "A flaw was found in python. In algorithms with quadratic time complexity using non-binary bases, when using int(\"text\"), a system could take 50ms to parse an int string with 100,000 digits and 5s for 1,000,000 digits (float, decimal, int.from_bytes(), and int() for binary bases 2, 4, 8, 16, and 32 are not affected). The highest threat from this vulnerability is to system availability.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-704"
        ],
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          }
        },
        "References": [
          "http://www.openwall.com/lists/oss-security/2022/09/21/1",
          "http://www.openwall.com/lists/oss-security/2022/09/21/4",
          "https://access.redhat.com/errata/RHSA-2022:7323",
          "https://access.redhat.com/security/cve/CVE-2020-10735",
          "https://bugzilla.redhat.com/1834423",
          "https://bugzilla.redhat.com/show_bug.cgi?id=1834423",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2120642",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2144072",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-10735",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-28861",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-45061",
          "https://docs.google.com/document/d/1KjuF_aXlzPUxTK4BMgezGJ2Pn7uevfX7g0_mvgHlL7Y",
          "https://errata.almalinux.org/9/ALSA-2022-7323.html",
          "https://errata.rockylinux.org/RLSA-2023:0833",
          "https://github.com/python/cpython/issues/95778",
          "https://linux.oracle.com/cve/CVE-2020-10735.html",
          "https://linux.oracle.com/errata/ELSA-2023-2764.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/2VCU6EVQDIXNCEDJUCTFIER2WVNNDTYZ/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/32AAQKABEKFCB5DDV5OONRZK6BS23HPW/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4EWKR2SPX3JORLWCXFY3KN2U5B5CIUQQ/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6XL6E5A3I36TRR73VNBOXNIQP4AMZDFZ/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/76YE7AM37MRU76XJV4M27CWDAMUGNRYK/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HSRPVJZL6DJFWKYRHMNJB7VCEUCBKRF5/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/IFGV7P2PYFBMK32OKHCAC2ZPJQV5AUDF/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NHC6IUU7CLRQ3QLPWUXLONSG3SXFTR47/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OKYE2DOI2X7WZXAWTQJZAXYIWM37HDCY/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OT5U223OE5ZOUHZAZYSYSWVJQIKDE73E/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OT5WQB7Z3CXOWVBD2AFAHYPA5ONYFFZ4/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PD7FTLJOIGMUSCDR3JAN6WRFHJEE4PH5/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SZYJSGLSCQOKXXFVJVJQAXLEOJBIWGEL/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/TD7JDDKJXK6D26XAN3YRFNM2LAJHT5UO/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/TMWPRAAJS7I6U3U45V7GZVXWNSECI22M/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/U4ZZV4CDFRMTPDBI7C5L43RFL3XLIGUY/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/UBPDVCDIUCEBE7C4NAGNA2KQJYOTPBAZ/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/V7ZUJDHK7KNG6SLIFXW7MNZ6O2PUJYK6/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/WXF6MQ74HVIDDSR5AE2UDR24I6D4FEPC/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ZEOAJWGGY55QU35UM2OVZATBW5MX2OZD/",
          "https://nvd.nist.gov/vuln/detail/CVE-2020-10735",
          "https://www.cve.org/CVERecord?id=CVE-2020-10735"
        ],
        "PublishedDate": "2022-09-09T14:15:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-3737",
        "PkgID": "libpython3.9-stdlib@3.9.2-1",
        "PkgName": "libpython3.9-stdlib",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e647281aeda207430048571c138604d8fcb88a8228cf3bab08e20602ff510002"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-3737",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "HTTP client possible infinite loop on a 100 Continue response",
        "Description": "A flaw was found in python. An improperly handled HTTP response in the HTTP client code of python may allow a remote attacker, who controls the HTTP server, to make the client script enter an infinite loop, consuming CPU time. The highest threat from this vulnerability is to system availability.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-400",
          "CWE-835"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:M/Au:N/C:N/I:N/A:C",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V2Score": 7.1,
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 6.5
          }
        },
        "References": [
          "https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-3737.json",
          "https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-4189.json",
          "https://access.redhat.com/security/cve/CVE-2021-3737",
          "https://bugs.python.org/issue44022",
          "https://bugzilla.redhat.com/show_bug.cgi?id=1995162",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3737",
          "https://errata.almalinux.org/8/ALSA-2022-1986.html",
          "https://github.com/python/cpython/commit/0389426fa4af4dfc8b1d7f3f291932d928392d8b (3.8 branch)",
          "https://github.com/python/cpython/commit/078b146f062d212919d0ba25e34e658a8234aa63 (v3.7.11)",
          "https://github.com/python/cpython/commit/1b6f4e5e13ebd1f957b47f7415b53d0869bdbac6 (v3.6.14",
          "https://github.com/python/cpython/commit/5df4abd6b033a5f1e48945c6988b45e35e76f647 (v3.9.6)",
          "https://github.com/python/cpython/commit/60ba0b68470a584103e28958d91e93a6db37ec92 (v3.10.0b2)",
          "https://github.com/python/cpython/commit/98e5a7975d99b58d511f171816ecdfb13d5cca18 (v3.10.0b3)",
          "https://github.com/python/cpython/commit/ea9327036680acc92d9f89eaf6f6a54d2f8d78d9 (v3.9.6)",
          "https://github.com/python/cpython/commit/f396864ddfe914531b5856d7bf852808ebfc01ae (v3.8.11)",
          "https://github.com/python/cpython/commit/f68d2d69f1da56c2aea1293ecf93ab69a6010ad7 (v3.6.14)",
          "https://github.com/python/cpython/commit/fee96422e6f0056561cf74fef2012cc066c9db86 (v3.7.11)",
          "https://github.com/python/cpython/pull/25916",
          "https://github.com/python/cpython/pull/26503",
          "https://linux.oracle.com/cve/CVE-2021-3737.html",
          "https://linux.oracle.com/errata/ELSA-2022-1986.html",
          "https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-3737",
          "https://python-security.readthedocs.io/vuln/urllib-100-continue-loop.html",
          "https://security.netapp.com/advisory/ntap-20220407-0009/",
          "https://ubuntu.com/security/CVE-2021-3737",
          "https://ubuntu.com/security/notices/USN-5083-1",
          "https://ubuntu.com/security/notices/USN-5199-1",
          "https://ubuntu.com/security/notices/USN-5200-1",
          "https://ubuntu.com/security/notices/USN-5201-1",
          "https://www.cve.org/CVERecord?id=CVE-2021-3737",
          "https://www.oracle.com/security-alerts/cpujul2022.html"
        ],
        "PublishedDate": "2022-03-04T19:15:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2022-0391",
        "PkgID": "libpython3.9-stdlib@3.9.2-1",
        "PkgName": "libpython3.9-stdlib",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e647281aeda207430048571c138604d8fcb88a8228cf3bab08e20602ff510002"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-0391",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: urllib.parse does not sanitize URLs containing ASCII newline and tabs",
        "Description": "A flaw was found in Python, specifically within the urllib.parse module. This module helps break Uniform Resource Locator (URL) strings into components. The issue involves how the urlparse method does not sanitize input and allows characters like '\\r' and '\\n' in the URL path. This flaw allows an attacker to input a crafted URL, leading to injection attacks. This flaw affects Python versions prior to 3.10.0b1, 3.9.5, 3.8.11, 3.7.11 and 3.6.14.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-74"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:N/I:P/A:N",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V2Score": 5,
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "V3Score": 5.3
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2022:6457",
          "https://access.redhat.com/security/cve/CVE-2022-0391",
          "https://bugs.python.org/issue43882",
          "https://bugzilla.redhat.com/2047376",
          "https://bugzilla.redhat.com/2075390",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-0391",
          "https://errata.almalinux.org/8/ALSA-2022-6457.html",
          "https://linux.oracle.com/cve/CVE-2022-0391.html",
          "https://linux.oracle.com/errata/ELSA-2023-3550.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CSD2YBXP3ZF44E44QMIIAR5VTO35KTRB/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UDBDBAU6HUPZHISBOARTXZ5GKHF2VH5U/",
          "https://nvd.nist.gov/vuln/detail/CVE-2022-0391",
          "https://security.gentoo.org/glsa/202305-02",
          "https://security.netapp.com/advisory/ntap-20220225-0009/",
          "https://ubuntu.com/security/notices/USN-5342-1",
          "https://ubuntu.com/security/notices/USN-5342-2",
          "https://www.cve.org/CVERecord?id=CVE-2022-0391",
          "https://www.oracle.com/security-alerts/cpuapr2022.html"
        ],
        "PublishedDate": "2022-02-09T23:15:00Z",
        "LastModifiedDate": "2023-05-03T11:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2022-42919",
        "PkgID": "libpython3.9-stdlib@3.9.2-1",
        "PkgName": "libpython3.9-stdlib",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e647281aeda207430048571c138604d8fcb88a8228cf3bab08e20602ff510002"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-42919",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "local privilege escalation via the multiprocessing forkserver start method",
        "Description": "Python 3.9.x before 3.9.16 and 3.10.x before 3.10.9 on Linux allows local privilege escalation in a non-default configuration. The Python multiprocessing library, when used with the forkserver start method on Linux, allows pickles to be deserialized from any user in the same machine local network namespace, which in many system configurations means any user on the same machine. Pickles can execute arbitrary code. Thus, this allows for local user privilege escalation to the user that any forkserver process is running as. Setting multiprocessing.util.abstract_sockets_supported to False is a workaround. The forkserver start method for multiprocessing is not the default start method. This issue is Linux specific because only Linux supports abstract namespace sockets. CPython before 3.9 does not make use of Linux abstract namespace sockets by default. Support for users manually specifying an abstract namespace socket was added as a bugfix in 3.7.8 and 3.8.3, but users would need to make specific uncommon API calls in order to do that in CPython before 3.9.",
        "Severity": "HIGH",
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 7.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 7.8
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2022:8493",
          "https://access.redhat.com/security/cve/CVE-2022-42919",
          "https://bugzilla.redhat.com/2138705",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2138705",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-42919",
          "https://errata.almalinux.org/9/ALSA-2022-8493.html",
          "https://errata.rockylinux.org/RLSA-2022:8493",
          "https://github.com/python/cpython/compare/v3.10.8...v3.10.9",
          "https://github.com/python/cpython/compare/v3.9.15...v3.9.16",
          "https://github.com/python/cpython/issues/97514",
          "https://github.com/python/cpython/issues/97514#issuecomment-1310277840",
          "https://linux.oracle.com/cve/CVE-2022-42919.html",
          "https://linux.oracle.com/errata/ELSA-2022-8493.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FKGCQPIVHEAIJ77R3RSNSQWYBUDVWDKU/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/P2LHWWEI5OBQ6RELULMVU6KMDYG4WZXH/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PI5DYIED6U26BGX5IRZWNCP6TY4M2ZGZ/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QLUGZSEAO3MBWGKCUSMKQIRYJZKJCIOB/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/R6KGIRHSENZ4QAB234Z36HVIDTRJ3MFI/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RDK3ZZBRYFO47ET3N4BNTKVXN47U6ICY/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VCRKBB5Y5EWTJUNC7LK665WO64DDXSTN/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XX6LLAXGZVZ327REY6MDZRMMP47LJ53P/",
          "https://nvd.nist.gov/vuln/detail/CVE-2022-42919",
          "https://python-security.readthedocs.io/vuln/multiprocessing-abstract-socket.html",
          "https://security.gentoo.org/glsa/202305-02",
          "https://security.netapp.com/advisory/ntap-20221209-0006/",
          "https://ubuntu.com/security/notices/USN-5713-1",
          "https://ubuntu.com/security/notices/USN-5888-1",
          "https://www.cve.org/CVERecord?id=CVE-2022-42919"
        ],
        "PublishedDate": "2022-11-07T00:15:00Z",
        "LastModifiedDate": "2023-05-03T11:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2022-45061",
        "PkgID": "libpython3.9-stdlib@3.9.2-1",
        "PkgName": "libpython3.9-stdlib",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e647281aeda207430048571c138604d8fcb88a8228cf3bab08e20602ff510002"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-45061",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "CPU denial of service via inefficient IDNA decoder",
        "Description": "An issue was discovered in Python before 3.11.1. An unnecessary quadratic algorithm exists in one path when processing some inputs to the IDNA (RFC 3490) decoder, such that a crafted, unreasonably long name being presented to the decoder could lead to a CPU denial of service. Hostnames are often supplied by remote servers that could be controlled by a malicious actor; in such a scenario, they could trigger excessive CPU consumption on the client attempting to make use of an attacker-supplied supposed hostname. For example, the attack payload could be placed in the Location header of an HTTP response with status code 302. A fix is planned in 3.11.1, 3.10.9, 3.9.16, 3.8.16, and 3.7.16.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-400"
        ],
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2023:0953",
          "https://access.redhat.com/security/cve/CVE-2022-45061",
          "https://bugzilla.redhat.com/2144072",
          "https://bugzilla.redhat.com/show_bug.cgi?id=1834423",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2120642",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2144072",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-10735",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-28861",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-45061",
          "https://errata.almalinux.org/9/ALSA-2023-0953.html",
          "https://errata.rockylinux.org/RLSA-2023:0833",
          "https://github.com/python/cpython/issues/98433",
          "https://github.com/python/cpython/pull/99092",
          "https://github.com/python/cpython/pull/99230 (3.9-branch)",
          "https://github.com/python/cpython/pull/99231 (3.8-branch)",
          "https://linux.oracle.com/cve/CVE-2022-45061.html",
          "https://linux.oracle.com/errata/ELSA-2023-2860.html",
          "https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2AOUKI72ACV6CHY2QUFO6VK2DNMVJ2MB/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/35YDIWCUMWTMDBWFRAVENFH6BLB65D6S/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4WBZJNSALFGMPYTINIF57HAAK46U72WQ/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/63FS6VHY4DCS74HBTEINUDOECQ2X6ZCH/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7WQPHKGNXUJC3TC3BDW5RKGROWRJVSFR/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B3YI6JYARWU6GULWOHNUROSACT54XFFS/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GTPVDZDATRQFE6KAT6B4BQIQ4GRHIIIJ/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IN26PWZTYG6IF3APLRXQJBVACQHZUPT2/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JCDJXNBHWXNYUTOEV4H2HCFSRKV3SYL3/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JTYVESWVBPD57ZJC35G5722Q6TS37WSB/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KNE4GMD45RGC2HWUAAIGTDHT5VJ2E4O4/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LKWAMPURWUV3DCCT4J7VHRF4NT2CFVBR/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O67LRHDTJWH544KXB6KY4HMHQLYDXFPK/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ORVCQGJCCAVLN4DJDTWGREFCUWXKQRML/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PLQ2BNZVBBAQPV3SPRU24ZD37UYJJS7W/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QLUGZSEAO3MBWGKCUSMKQIRYJZKJCIOB/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RDK3ZZBRYFO47ET3N4BNTKVXN47U6ICY/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RH57BNT4VQERGEJ5SXNXSVMDYP66YD4H/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RTN2OOLKYTG34DODUEJGT5MLC2PFGPBA/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T3D5TX4TDJPXHXD2QICKTY3OCQC3JARP/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UHVW73QZJMHA4MK7JBT7CXX7XSNYQEGF/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VCMDX6IFKLOA3NXUQEV524L5LHTPI2JI/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/X3EJ6J7PXVQOULBQZQGBXCXY6LFF6LZD/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XXZJL3CNAFS5PAIR7K4RL62S3Y7THR7O/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YPNWZKXPKTNHS5FVMN7UQZ2UPCSEFJUK/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZB5YCMIRVX35RUB6XPOWKENCVCJEVDRK/",
          "https://nvd.nist.gov/vuln/detail/CVE-2022-45061",
          "https://python-security.readthedocs.io/vuln/slow-idna-large-strings.html",
          "https://security.gentoo.org/glsa/202305-02",
          "https://security.netapp.com/advisory/ntap-20221209-0007/",
          "https://ubuntu.com/security/notices/USN-5767-1",
          "https://ubuntu.com/security/notices/USN-5767-2",
          "https://ubuntu.com/security/notices/USN-5888-1",
          "https://www.cve.org/CVERecord?id=CVE-2022-45061"
        ],
        "PublishedDate": "2022-11-09T07:15:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2023-24329",
        "PkgID": "libpython3.9-stdlib@3.9.2-1",
        "PkgName": "libpython3.9-stdlib",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e647281aeda207430048571c138604d8fcb88a8228cf3bab08e20602ff510002"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-24329",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "urllib.parse url blocklisting bypass",
        "Description": "An issue in the urllib.parse component of Python before 3.11.4 allows attackers to bypass blocklisting methods by supplying a URL that starts with blank characters.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-20"
        ],
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2023:3595",
          "https://access.redhat.com/security/cve/CVE-2023-24329",
          "https://bugzilla.redhat.com/2173917",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2173917",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-24329",
          "https://errata.almalinux.org/9/ALSA-2023-3595.html",
          "https://errata.rockylinux.org/RLSA-2023:3591",
          "https://github.com/python/cpython/issues/102153",
          "https://github.com/python/cpython/pull/99421",
          "https://github.com/python/cpython/pull/99446 (backport for 3.11 branch)",
          "https://linux.oracle.com/cve/CVE-2023-24329.html",
          "https://linux.oracle.com/errata/ELSA-2023-3595.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6PEVICI7YNGGMSL3UCMWGE66QFLATH72/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DSL6NSOAXWBJJ67XPLSSC74MNKZF3BBO/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/EM2XLZSTXG44TMFXF4E6VTGKR2MQCW3G/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/F2NY75GFDZ5T6YPN44D3VMFT5SUVTOTG/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GR5US3BYILYJ4SKBV6YBNPRUBAL5P2CN/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/H23OSKC6UG6IWOQAUPW74YUHWRWVXJP7/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JZTLGV2HYFF4AMYJL25VDIGAIHCU7UPA/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LWC4WGXER5P6Q75RFGL7QUTPP3N5JR7T/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MZEHSXSCMA4WWQKXT6QV7AAR6SWNZ2VP/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O5SP4RT3RRS434ZS2HQKQJ3VZW7YPKYR/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OHHJHJRLEF3TDT2K3676CAUVRDD4CCMR/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PEUN6T22UJFXR7J5F6UUHCXXPKJ2DVHI/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PURM5CFDABEWAIWZFD2MQ7ZJGCPYSQ44/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/Q3J5N24ECS4B6MJDRO6UAYU6GPLYBDCL/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QRQHN7RWJQJHYP6E5EKESOYP5VDSHZG4/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RA2MBEEES6L46OD64OBSVUUMGKNGMOWW/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T4IDB5OAR5Y4UK3HLMZBW4WEL2B7YFMJ/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TZH26JGNZ5XYPZ5SAU3NKSBSPRE5OHTG/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/U2MZOJYGFCB5PPT6AKMAU72N7QOYWLBP/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UONZWLB4QVLQIY5CPDLEUEKH6WX4VQMC/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WTOAUJNDWZDRWVSXJ354AYZYKRMT56HU/",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-24329",
          "https://pointernull.com/security/python-url-parse-problem.html",
          "https://security.netapp.com/advisory/ntap-20230324-0004/",
          "https://ubuntu.com/security/notices/USN-5888-1",
          "https://ubuntu.com/security/notices/USN-5960-1",
          "https://ubuntu.com/security/notices/USN-6139-1",
          "https://www.cve.org/CVERecord?id=CVE-2023-24329"
        ],
        "PublishedDate": "2023-02-17T15:15:00Z",
        "LastModifiedDate": "2023-06-16T04:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-3426",
        "PkgID": "libpython3.9-stdlib@3.9.2-1",
        "PkgName": "libpython3.9-stdlib",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e647281aeda207430048571c138604d8fcb88a8228cf3bab08e20602ff510002"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-3426",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: Information disclosure via pydoc",
        "Description": "There's a flaw in Python 3's pydoc. A local or adjacent attacker who discovers or is able to convince another local or adjacent user to start a pydoc server could access the server and use it to disclose sensitive information belonging to the other user that they would not normally be able to access. The highest risk of this flaw is to data confidentiality. This flaw affects Python versions before 3.8.9, Python versions before 3.9.3 and Python versions before 3.10.0a7.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-22"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:A/AC:L/Au:S/C:P/I:N/A:N",
            "V3Vector": "CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
            "V2Score": 2.7,
            "V3Score": 5.7
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
            "V3Score": 5.7
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2021-3426",
          "https://bugzilla.redhat.com/show_bug.cgi?id=1935913",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3426",
          "https://github.com/python/cpython/pull/24285",
          "https://github.com/python/cpython/pull/24337",
          "https://linux.oracle.com/cve/CVE-2021-3426.html",
          "https://linux.oracle.com/errata/ELSA-2021-9562.html",
          "https://lists.debian.org/debian-lts-announce/2021/04/msg00005.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/25HVHLBGO2KNPXJ3G426QEYSSCECJDU5/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BF2K7HEWADHN6P52R3QLIOX27U3DJ4HI/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DQYPUKLLBOZMKFPO7RD7CENTXHUUEUV7/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LM5V4VPLBHBEASSAROYPSHXGXGGPHNOE/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N6VXJZSZ6N64AILJX4CTMACYGQGHHD5C/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QNGAFMPIYIVJ47FCF2NK2PIX22HUG35B/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VPX7Y5GQDNB4FJTREWONGC4ZSVH7TGHF/",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-3426",
          "https://python-security.readthedocs.io/vuln/pydoc-getfile.html",
          "https://security.gentoo.org/glsa/202104-04",
          "https://security.netapp.com/advisory/ntap-20210629-0003/",
          "https://ubuntu.com/security/notices/USN-5342-1",
          "https://ubuntu.com/security/notices/USN-5342-3",
          "https://www.cve.org/CVERecord?id=CVE-2021-3426",
          "https://www.oracle.com/security-alerts/cpujan2022.html",
          "https://www.oracle.com/security-alerts/cpuoct2021.html"
        ],
        "PublishedDate": "2021-05-20T13:15:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-3733",
        "PkgID": "libpython3.9-stdlib@3.9.2-1",
        "PkgName": "libpython3.9-stdlib",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e647281aeda207430048571c138604d8fcb88a8228cf3bab08e20602ff510002"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-3733",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: urllib: Regular expression DoS in AbstractBasicAuthHandler",
        "Description": "There's a flaw in urllib's AbstractBasicAuthHandler class. An attacker who controls a malicious HTTP server that an HTTP client (such as web browser) connects to, could trigger a Regular Expression Denial of Service (ReDOS) during an authentication request with a specially crafted payload that is sent by the server to the client. The greatest threat that this flaw poses is to application availability.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-400"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:S/C:N/I:N/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
            "V2Score": 4,
            "V3Score": 6.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 6.5
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2021-3733",
          "https://bugs.python.org/issue43075",
          "https://bugzilla.redhat.com/show_bug.cgi?id=1995234",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3733",
          "https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-14-final",
          "https://docs.python.org/3.7/whatsnew/changelog.html#python-3-7-11-final",
          "https://docs.python.org/3.8/whatsnew/changelog.html#python-3-8-10-final",
          "https://docs.python.org/3.9/whatsnew/changelog.html#python-3-9-5-final",
          "https://errata.almalinux.org/8/ALSA-2022-1821.html",
          "https://github.com/python/cpython/commit/3fbe96123aeb66664fa547a8f6022efa2dc8788f (3.6.14)",
          "https://github.com/python/cpython/commit/7215d1ae25525c92b026166f9d5cac85fb",
          "https://github.com/python/cpython/commit/7215d1ae25525c92b026166f9d5cac85fb1defe1 (master)",
          "https://github.com/python/cpython/commit/a21d4fbd549ec9685068a113660553d7f80d9b09 (3.9.5)",
          "https://github.com/python/cpython/commit/ada14995870abddc277addf57dd690a2af04c2da (3.7.11)",
          "https://github.com/python/cpython/commit/e7654b6046090914a8323931ed759a94a5f85d60 (3.8.10)",
          "https://github.com/python/cpython/pull/24391",
          "https://linux.oracle.com/cve/CVE-2021-3733.html",
          "https://linux.oracle.com/errata/ELSA-2022-1821.html",
          "https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-3733",
          "https://security.netapp.com/advisory/ntap-20220407-0001/",
          "https://ubuntu.com/security/CVE-2021-3733",
          "https://ubuntu.com/security/notices/USN-5083-1",
          "https://ubuntu.com/security/notices/USN-5199-1",
          "https://ubuntu.com/security/notices/USN-5200-1",
          "https://www.cve.org/CVERecord?id=CVE-2021-3733"
        ],
        "PublishedDate": "2022-03-10T17:42:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-4189",
        "PkgID": "libpython3.9-stdlib@3.9.2-1",
        "PkgName": "libpython3.9-stdlib",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e647281aeda207430048571c138604d8fcb88a8228cf3bab08e20602ff510002"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-4189",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "ftplib should not use the host from the PASV response",
        "Description": "A flaw was found in Python, specifically in the FTP (File Transfer Protocol) client library in PASV (passive) mode. The issue is how the FTP client trusts the host from the PASV response by default. This flaw allows an attacker to set up a malicious FTP server that can trick FTP clients into connecting back to a given IP address and port. This vulnerability could lead to FTP client scanning ports, which otherwise would not have been possible.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-252"
        ],
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "V3Score": 5.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "V3Score": 5.3
          }
        },
        "References": [
          "https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-3737.json",
          "https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-4189.json",
          "https://access.redhat.com/security/cve/CVE-2021-4189",
          "https://bugs.python.org/issue43285",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2036020",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-4189",
          "https://errata.almalinux.org/8/ALSA-2022-1986.html",
          "https://github.com/python/cpython/commit/0ab152c6b5d95caa2dc1a30fa96e10258b5f188e",
          "https://github.com/python/cpython/commit/0ab152c6b5d95caa2dc1a30fa96e10258b5f188e (master)",
          "https://github.com/python/cpython/commit/4134f154ae2f621f25c5d698cc0f1748035a1b88 (v3.6.14)",
          "https://github.com/python/cpython/commit/79373951b3eab585d42e0f0ab83718cbe1d0ee33 (v3.7.11)",
          "https://github.com/python/cpython/commit/7dcb4baa4f0fde3aef5122a8e9f6a41853ec9335 (v3.9.3)",
          "https://linux.oracle.com/cve/CVE-2021-4189.html",
          "https://linux.oracle.com/errata/ELSA-2022-1986.html",
          "https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-4189",
          "https://python-security.readthedocs.io/vuln/ftplib-pasv.html",
          "https://security-tracker.debian.org/tracker/CVE-2021-4189",
          "https://security.netapp.com/advisory/ntap-20221104-0004/",
          "https://ubuntu.com/security/notices/USN-5342-1",
          "https://ubuntu.com/security/notices/USN-5342-2",
          "https://www.cve.org/CVERecord?id=CVE-2021-4189"
        ],
        "PublishedDate": "2022-08-24T16:15:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2023-27043",
        "PkgID": "libpython3.9-stdlib@3.9.2-1",
        "PkgName": "libpython3.9-stdlib",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e647281aeda207430048571c138604d8fcb88a8228cf3bab08e20602ff510002"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-27043",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "Parsing errors in email/_parseaddr.py lead to incorrect value in email address part of tuple",
        "Description": "The email module of Python through 3.11.3 incorrectly parses e-mail addresses that contain a special character. The wrong portion of an RFC2822 header is identified as the value of the addr-spec. In some applications, an attacker can bypass a protection mechanism in which application access is granted only after verifying receipt of e-mail to a specific domain (e.g., only @company.example.com addresses may be used for signup). This occurs in email/_parseaddr.py in recent versions of Python.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-20"
        ],
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "V3Score": 5.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "V3Score": 5.3
          }
        },
        "References": [
          "http://python.org",
          "https://access.redhat.com/security/cve/CVE-2023-27043",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-27043",
          "https://github.com/python/cpython/issues/102988",
          "https://github.com/python/cpython/pull/102990",
          "https://github.com/python/cpython/pull/105127",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-27043",
          "https://python-security.readthedocs.io/vuln/email-parseaddr-realname.html",
          "https://security.netapp.com/advisory/ntap-20230601-0003/",
          "https://www.cve.org/CVERecord?id=CVE-2023-27043"
        ],
        "PublishedDate": "2023-04-19T00:15:00Z",
        "LastModifiedDate": "2023-06-01T14:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-31239",
        "PkgID": "libsqlite3-0@3.34.1-3",
        "PkgName": "libsqlite3-0",
        "InstalledVersion": "3.34.1-3",
        "Layer": {
          "DiffID": "sha256:0361602fcfc1e5e1da3c9fa364f84e56c0c963cf7407a8db8e6c47595b1985f2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-31239",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "denial of service via the appendvfs.c function",
        "Description": "An issue found in SQLite SQLite3 v.3.35.4 that allows a remote attacker to cause a denial of service via the appendvfs.c function.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-125"
        ],
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2021-31239",
          "https://github.com/Tsiming/Vulnerabilities/blob/main/SQLite/CVE-2021-31239",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/73XUIHJ6UT75VFPDPLJOXJON7MVIKVZI/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXFL4TDAH72PRCPD5UPZMJMKIMVOPLTI/",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-31239",
          "https://security.netapp.com/advisory/ntap-20230609-0010/",
          "https://www.cve.org/CVERecord?id=CVE-2021-31239",
          "https://www.sqlite.org/cves.html",
          "https://www.sqlite.org/forum/forumpost/d9fce1a89b"
        ],
        "PublishedDate": "2023-05-09T02:15:00Z",
        "LastModifiedDate": "2023-06-09T08:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2023-29491",
        "PkgID": "libtinfo6@6.2+20201114-2+deb11u1",
        "PkgName": "libtinfo6",
        "InstalledVersion": "6.2+20201114-2+deb11u1",
        "Layer": {
          "DiffID": "sha256:0e24676df88c8a6bcf6a270973214fdee7130182aa3d66fd6ead477979b41d5f"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-29491",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "Local users can trigger security-relevant memory corruption via malformed data",
        "Description": "ncurses before 6.4 20230408, when used by a setuid application, allows local users to trigger security-relevant memory corruption via malformed data in a terminfo database file that is found in $HOME/.terminfo or reached via the TERMINFO or TERM environment variable.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-787"
        ],
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 7.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 7.8
          }
        },
        "References": [
          "http://ncurses.scripts.mit.edu/?p=ncurses.git;a=commit;h=eb51b1ea1f75a0ec17c9c5937cb28df1e8eeec56",
          "http://www.openwall.com/lists/oss-security/2023/04/19/10",
          "http://www.openwall.com/lists/oss-security/2023/04/19/11",
          "https://access.redhat.com/security/cve/CVE-2023-29491",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-29491",
          "https://invisible-island.net/ncurses/NEWS.html#index-t20230408",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-29491",
          "https://security.netapp.com/advisory/ntap-20230517-0009/",
          "https://ubuntu.com/security/notices/USN-6099-1",
          "https://www.cve.org/CVERecord?id=CVE-2023-29491",
          "https://www.openwall.com/lists/oss-security/2023/04/12/5",
          "https://www.openwall.com/lists/oss-security/2023/04/13/4"
        ],
        "PublishedDate": "2023-04-14T01:15:00Z",
        "LastModifiedDate": "2023-05-17T20:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-29921",
        "PkgID": "python3.9-minimal@3.9.2-1",
        "PkgName": "python3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e0ec835c1f88840979da9a3ea10e58ca594d79d44d4e4871cc2e5043eaaa83b8"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-29921",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python-ipaddress: Improper input validation of octal strings",
        "Description": "In Python before 3,9,5, the ipaddress library mishandles leading zero characters in the octets of an IP address string. This (in some situations) allows attackers to bypass access control that is based on IP addresses.",
        "Severity": "CRITICAL",
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V2Score": 7.5,
            "V3Score": 9.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
            "V3Score": 9.1
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2021-29921",
          "https://bugs.python.org/issue36384",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-29921",
          "https://docs.python.org/3/library/ipaddress.html",
          "https://errata.almalinux.org/8/ALSA-2021-4162.html",
          "https://github.com/python/cpython/blob/63298930fb531ba2bb4f23bc3b915dbf1e17e9e1/Misc/NEWS.d/3.8.0a4.rst",
          "https://github.com/python/cpython/pull/12577",
          "https://github.com/python/cpython/pull/25099",
          "https://github.com/sickcodes",
          "https://github.com/sickcodes/security/blob/master/advisories/SICK-2021-014.md",
          "https://linux.oracle.com/cve/CVE-2021-29921.html",
          "https://linux.oracle.com/errata/ELSA-2021-4162.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-29921",
          "https://python-security.readthedocs.io/vuln/ipaddress-ipv4-leading-zeros.html",
          "https://security.gentoo.org/glsa/202305-02",
          "https://security.netapp.com/advisory/ntap-20210622-0003/",
          "https://sick.codes/sick-2021-014",
          "https://ubuntu.com/security/notices/USN-4973-1",
          "https://ubuntu.com/security/notices/USN-4973-2",
          "https://www.cve.org/CVERecord?id=CVE-2021-29921",
          "https://www.oracle.com//security-alerts/cpujul2021.html",
          "https://www.oracle.com/security-alerts/cpuapr2022.html",
          "https://www.oracle.com/security-alerts/cpujan2022.html",
          "https://www.oracle.com/security-alerts/cpujul2022.html",
          "https://www.oracle.com/security-alerts/cpuoct2021.html"
        ],
        "PublishedDate": "2021-05-06T13:15:00Z",
        "LastModifiedDate": "2023-05-03T11:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2015-20107",
        "PkgID": "python3.9-minimal@3.9.2-1",
        "PkgName": "python3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e0ec835c1f88840979da9a3ea10e58ca594d79d44d4e4871cc2e5043eaaa83b8"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2015-20107",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: mailcap: findmatch() function does not sanitize the second argument",
        "Description": "In Python (aka CPython) up to 3.10.8, the mailcap module does not add escape characters into commands discovered in the system mailcap file. This may allow attackers to inject shell commands into applications that call mailcap.findmatch with untrusted input (if they lack validation of user-provided filenames or arguments). The fix is also back-ported to 3.7, 3.8, 3.9",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-77"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:S/C:P/I:C/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:H/A:L",
            "V2Score": 8,
            "V3Score": 7.6
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:H/A:L",
            "V3Score": 7.6
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2022:8353",
          "https://access.redhat.com/security/cve/CVE-2015-20107",
          "https://bugs.python.org/issue24778",
          "https://bugzilla.redhat.com/2075390",
          "https://bugzilla.redhat.com/2120642",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2054702",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2059951",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2075390",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2120642",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2128249",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-20107",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-28861",
          "https://errata.almalinux.org/9/ALSA-2022-8353.html",
          "https://errata.rockylinux.org/RLSA-2022:8353",
          "https://github.com/python/cpython/issues/68966",
          "https://github.com/python/cpython/pull/91542/commits/340251550897cb98ae83ad1040750d6300112e80",
          "https://github.com/python/cpython/pull/91993",
          "https://linux.oracle.com/cve/CVE-2015-20107.html",
          "https://linux.oracle.com/errata/ELSA-2022-8353.html",
          "https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/46KWPTI72SSEOF53DOYQBQOCN4QQB2GE/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/53TQZFLS6O3FLIMVSXFEEPZSWLDZLBOX/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/57NECACX333A3BBZM2TR2VZ4ZE3UG3SN/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5DBVY4YC2P6EPZZ2DROOXHDOWZ4BJFLW/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6QIKVSW3H6W2GQGDE5DTIWLGFNH6KKEW/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AKGMYDVKI3XNM27B6I6RQ6QV3TVJAUCG/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ERYMM2QVDPOJLX4LYXWYIQN5FOIJLDRY/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/F3LNY2NHM6J22O6Q5ANOE3SZRK3OACKR/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FCIO2W4DUVVMI6L52QCC4TT2B3K5VWHS/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FIRUTX47BJD2HYJDLMI7JJBVCYFAPKAQ/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GPCLGZZJPVXFWUWVV5WCD5FNUAFLKBDN/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HAI2GBC7WKH7J5NH6J2IW5RT3VF2SF5M/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IFGV7P2PYFBMK32OKHCAC2ZPJQV5AUDF/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KAY6VBNVEFUXKJF37WFHYXUSRDEK34N3/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MYG3EMFR7ZHC46TDNM7SNWO64A3W7EUF/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ONXSGLASNLGFL57YU6WT6Y5YURSFV43U/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PTTZGLD2YBMMG6U6F5HOTPOGGPBIURMA/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UIOJUZ5JMEMGSKNISTOVI4PDP36FDL5Y/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/W5664BGZVTA46LQDNTYX5THG6CN4FYJX/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WXF6MQ74HVIDDSR5AE2UDR24I6D4FEPC/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XO2H6CKWLRGTTZCGUQVELW6LUH437Q3O/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/Y4E2WBEJ42CGLGDHD6ZXOLZ2W6G3YOVD/",
          "https://mail.python.org/archives/list/security-announce@python.org/thread/QDSXNCW77UGULFG2JMDFZQ7H4DIR32LA/",
          "https://nvd.nist.gov/vuln/detail/CVE-2015-20107",
          "https://python-security.readthedocs.io/vuln/mailcap-shell-injection.html",
          "https://security.gentoo.org/glsa/202305-02",
          "https://security.netapp.com/advisory/ntap-20220616-0001/",
          "https://ubuntu.com/security/notices/USN-5519-1",
          "https://ubuntu.com/security/notices/USN-5888-1",
          "https://www.cve.org/CVERecord?id=CVE-2015-20107"
        ],
        "PublishedDate": "2022-04-13T16:15:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2020-10735",
        "PkgID": "python3.9-minimal@3.9.2-1",
        "PkgName": "python3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e0ec835c1f88840979da9a3ea10e58ca594d79d44d4e4871cc2e5043eaaa83b8"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-10735",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "int() type in PyLong_FromString() does not limit amount of digits converting text to int leading to DoS",
        "Description": "A flaw was found in python. In algorithms with quadratic time complexity using non-binary bases, when using int(\"text\"), a system could take 50ms to parse an int string with 100,000 digits and 5s for 1,000,000 digits (float, decimal, int.from_bytes(), and int() for binary bases 2, 4, 8, 16, and 32 are not affected). The highest threat from this vulnerability is to system availability.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-704"
        ],
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          }
        },
        "References": [
          "http://www.openwall.com/lists/oss-security/2022/09/21/1",
          "http://www.openwall.com/lists/oss-security/2022/09/21/4",
          "https://access.redhat.com/errata/RHSA-2022:7323",
          "https://access.redhat.com/security/cve/CVE-2020-10735",
          "https://bugzilla.redhat.com/1834423",
          "https://bugzilla.redhat.com/show_bug.cgi?id=1834423",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2120642",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2144072",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-10735",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-28861",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-45061",
          "https://docs.google.com/document/d/1KjuF_aXlzPUxTK4BMgezGJ2Pn7uevfX7g0_mvgHlL7Y",
          "https://errata.almalinux.org/9/ALSA-2022-7323.html",
          "https://errata.rockylinux.org/RLSA-2023:0833",
          "https://github.com/python/cpython/issues/95778",
          "https://linux.oracle.com/cve/CVE-2020-10735.html",
          "https://linux.oracle.com/errata/ELSA-2023-2764.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/2VCU6EVQDIXNCEDJUCTFIER2WVNNDTYZ/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/32AAQKABEKFCB5DDV5OONRZK6BS23HPW/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4EWKR2SPX3JORLWCXFY3KN2U5B5CIUQQ/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6XL6E5A3I36TRR73VNBOXNIQP4AMZDFZ/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/76YE7AM37MRU76XJV4M27CWDAMUGNRYK/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HSRPVJZL6DJFWKYRHMNJB7VCEUCBKRF5/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/IFGV7P2PYFBMK32OKHCAC2ZPJQV5AUDF/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NHC6IUU7CLRQ3QLPWUXLONSG3SXFTR47/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OKYE2DOI2X7WZXAWTQJZAXYIWM37HDCY/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OT5U223OE5ZOUHZAZYSYSWVJQIKDE73E/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OT5WQB7Z3CXOWVBD2AFAHYPA5ONYFFZ4/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PD7FTLJOIGMUSCDR3JAN6WRFHJEE4PH5/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SZYJSGLSCQOKXXFVJVJQAXLEOJBIWGEL/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/TD7JDDKJXK6D26XAN3YRFNM2LAJHT5UO/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/TMWPRAAJS7I6U3U45V7GZVXWNSECI22M/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/U4ZZV4CDFRMTPDBI7C5L43RFL3XLIGUY/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/UBPDVCDIUCEBE7C4NAGNA2KQJYOTPBAZ/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/V7ZUJDHK7KNG6SLIFXW7MNZ6O2PUJYK6/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/WXF6MQ74HVIDDSR5AE2UDR24I6D4FEPC/",
          "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ZEOAJWGGY55QU35UM2OVZATBW5MX2OZD/",
          "https://nvd.nist.gov/vuln/detail/CVE-2020-10735",
          "https://www.cve.org/CVERecord?id=CVE-2020-10735"
        ],
        "PublishedDate": "2022-09-09T14:15:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-3737",
        "PkgID": "python3.9-minimal@3.9.2-1",
        "PkgName": "python3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e0ec835c1f88840979da9a3ea10e58ca594d79d44d4e4871cc2e5043eaaa83b8"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-3737",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "HTTP client possible infinite loop on a 100 Continue response",
        "Description": "A flaw was found in python. An improperly handled HTTP response in the HTTP client code of python may allow a remote attacker, who controls the HTTP server, to make the client script enter an infinite loop, consuming CPU time. The highest threat from this vulnerability is to system availability.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-400",
          "CWE-835"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:M/Au:N/C:N/I:N/A:C",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V2Score": 7.1,
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 6.5
          }
        },
        "References": [
          "https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-3737.json",
          "https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-4189.json",
          "https://access.redhat.com/security/cve/CVE-2021-3737",
          "https://bugs.python.org/issue44022",
          "https://bugzilla.redhat.com/show_bug.cgi?id=1995162",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3737",
          "https://errata.almalinux.org/8/ALSA-2022-1986.html",
          "https://github.com/python/cpython/commit/0389426fa4af4dfc8b1d7f3f291932d928392d8b (3.8 branch)",
          "https://github.com/python/cpython/commit/078b146f062d212919d0ba25e34e658a8234aa63 (v3.7.11)",
          "https://github.com/python/cpython/commit/1b6f4e5e13ebd1f957b47f7415b53d0869bdbac6 (v3.6.14",
          "https://github.com/python/cpython/commit/5df4abd6b033a5f1e48945c6988b45e35e76f647 (v3.9.6)",
          "https://github.com/python/cpython/commit/60ba0b68470a584103e28958d91e93a6db37ec92 (v3.10.0b2)",
          "https://github.com/python/cpython/commit/98e5a7975d99b58d511f171816ecdfb13d5cca18 (v3.10.0b3)",
          "https://github.com/python/cpython/commit/ea9327036680acc92d9f89eaf6f6a54d2f8d78d9 (v3.9.6)",
          "https://github.com/python/cpython/commit/f396864ddfe914531b5856d7bf852808ebfc01ae (v3.8.11)",
          "https://github.com/python/cpython/commit/f68d2d69f1da56c2aea1293ecf93ab69a6010ad7 (v3.6.14)",
          "https://github.com/python/cpython/commit/fee96422e6f0056561cf74fef2012cc066c9db86 (v3.7.11)",
          "https://github.com/python/cpython/pull/25916",
          "https://github.com/python/cpython/pull/26503",
          "https://linux.oracle.com/cve/CVE-2021-3737.html",
          "https://linux.oracle.com/errata/ELSA-2022-1986.html",
          "https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-3737",
          "https://python-security.readthedocs.io/vuln/urllib-100-continue-loop.html",
          "https://security.netapp.com/advisory/ntap-20220407-0009/",
          "https://ubuntu.com/security/CVE-2021-3737",
          "https://ubuntu.com/security/notices/USN-5083-1",
          "https://ubuntu.com/security/notices/USN-5199-1",
          "https://ubuntu.com/security/notices/USN-5200-1",
          "https://ubuntu.com/security/notices/USN-5201-1",
          "https://www.cve.org/CVERecord?id=CVE-2021-3737",
          "https://www.oracle.com/security-alerts/cpujul2022.html"
        ],
        "PublishedDate": "2022-03-04T19:15:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2022-0391",
        "PkgID": "python3.9-minimal@3.9.2-1",
        "PkgName": "python3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e0ec835c1f88840979da9a3ea10e58ca594d79d44d4e4871cc2e5043eaaa83b8"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-0391",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: urllib.parse does not sanitize URLs containing ASCII newline and tabs",
        "Description": "A flaw was found in Python, specifically within the urllib.parse module. This module helps break Uniform Resource Locator (URL) strings into components. The issue involves how the urlparse method does not sanitize input and allows characters like '\\r' and '\\n' in the URL path. This flaw allows an attacker to input a crafted URL, leading to injection attacks. This flaw affects Python versions prior to 3.10.0b1, 3.9.5, 3.8.11, 3.7.11 and 3.6.14.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-74"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:N/I:P/A:N",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V2Score": 5,
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "V3Score": 5.3
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2022:6457",
          "https://access.redhat.com/security/cve/CVE-2022-0391",
          "https://bugs.python.org/issue43882",
          "https://bugzilla.redhat.com/2047376",
          "https://bugzilla.redhat.com/2075390",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-0391",
          "https://errata.almalinux.org/8/ALSA-2022-6457.html",
          "https://linux.oracle.com/cve/CVE-2022-0391.html",
          "https://linux.oracle.com/errata/ELSA-2023-3550.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CSD2YBXP3ZF44E44QMIIAR5VTO35KTRB/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UDBDBAU6HUPZHISBOARTXZ5GKHF2VH5U/",
          "https://nvd.nist.gov/vuln/detail/CVE-2022-0391",
          "https://security.gentoo.org/glsa/202305-02",
          "https://security.netapp.com/advisory/ntap-20220225-0009/",
          "https://ubuntu.com/security/notices/USN-5342-1",
          "https://ubuntu.com/security/notices/USN-5342-2",
          "https://www.cve.org/CVERecord?id=CVE-2022-0391",
          "https://www.oracle.com/security-alerts/cpuapr2022.html"
        ],
        "PublishedDate": "2022-02-09T23:15:00Z",
        "LastModifiedDate": "2023-05-03T11:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2022-42919",
        "PkgID": "python3.9-minimal@3.9.2-1",
        "PkgName": "python3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e0ec835c1f88840979da9a3ea10e58ca594d79d44d4e4871cc2e5043eaaa83b8"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-42919",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "local privilege escalation via the multiprocessing forkserver start method",
        "Description": "Python 3.9.x before 3.9.16 and 3.10.x before 3.10.9 on Linux allows local privilege escalation in a non-default configuration. The Python multiprocessing library, when used with the forkserver start method on Linux, allows pickles to be deserialized from any user in the same machine local network namespace, which in many system configurations means any user on the same machine. Pickles can execute arbitrary code. Thus, this allows for local user privilege escalation to the user that any forkserver process is running as. Setting multiprocessing.util.abstract_sockets_supported to False is a workaround. The forkserver start method for multiprocessing is not the default start method. This issue is Linux specific because only Linux supports abstract namespace sockets. CPython before 3.9 does not make use of Linux abstract namespace sockets by default. Support for users manually specifying an abstract namespace socket was added as a bugfix in 3.7.8 and 3.8.3, but users would need to make specific uncommon API calls in order to do that in CPython before 3.9.",
        "Severity": "HIGH",
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 7.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 7.8
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2022:8493",
          "https://access.redhat.com/security/cve/CVE-2022-42919",
          "https://bugzilla.redhat.com/2138705",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2138705",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-42919",
          "https://errata.almalinux.org/9/ALSA-2022-8493.html",
          "https://errata.rockylinux.org/RLSA-2022:8493",
          "https://github.com/python/cpython/compare/v3.10.8...v3.10.9",
          "https://github.com/python/cpython/compare/v3.9.15...v3.9.16",
          "https://github.com/python/cpython/issues/97514",
          "https://github.com/python/cpython/issues/97514#issuecomment-1310277840",
          "https://linux.oracle.com/cve/CVE-2022-42919.html",
          "https://linux.oracle.com/errata/ELSA-2022-8493.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FKGCQPIVHEAIJ77R3RSNSQWYBUDVWDKU/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/P2LHWWEI5OBQ6RELULMVU6KMDYG4WZXH/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PI5DYIED6U26BGX5IRZWNCP6TY4M2ZGZ/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QLUGZSEAO3MBWGKCUSMKQIRYJZKJCIOB/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/R6KGIRHSENZ4QAB234Z36HVIDTRJ3MFI/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RDK3ZZBRYFO47ET3N4BNTKVXN47U6ICY/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VCRKBB5Y5EWTJUNC7LK665WO64DDXSTN/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XX6LLAXGZVZ327REY6MDZRMMP47LJ53P/",
          "https://nvd.nist.gov/vuln/detail/CVE-2022-42919",
          "https://python-security.readthedocs.io/vuln/multiprocessing-abstract-socket.html",
          "https://security.gentoo.org/glsa/202305-02",
          "https://security.netapp.com/advisory/ntap-20221209-0006/",
          "https://ubuntu.com/security/notices/USN-5713-1",
          "https://ubuntu.com/security/notices/USN-5888-1",
          "https://www.cve.org/CVERecord?id=CVE-2022-42919"
        ],
        "PublishedDate": "2022-11-07T00:15:00Z",
        "LastModifiedDate": "2023-05-03T11:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2022-45061",
        "PkgID": "python3.9-minimal@3.9.2-1",
        "PkgName": "python3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e0ec835c1f88840979da9a3ea10e58ca594d79d44d4e4871cc2e5043eaaa83b8"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-45061",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "CPU denial of service via inefficient IDNA decoder",
        "Description": "An issue was discovered in Python before 3.11.1. An unnecessary quadratic algorithm exists in one path when processing some inputs to the IDNA (RFC 3490) decoder, such that a crafted, unreasonably long name being presented to the decoder could lead to a CPU denial of service. Hostnames are often supplied by remote servers that could be controlled by a malicious actor; in such a scenario, they could trigger excessive CPU consumption on the client attempting to make use of an attacker-supplied supposed hostname. For example, the attack payload could be placed in the Location header of an HTTP response with status code 302. A fix is planned in 3.11.1, 3.10.9, 3.9.16, 3.8.16, and 3.7.16.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-400"
        ],
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2023:0953",
          "https://access.redhat.com/security/cve/CVE-2022-45061",
          "https://bugzilla.redhat.com/2144072",
          "https://bugzilla.redhat.com/show_bug.cgi?id=1834423",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2120642",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2144072",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-10735",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-28861",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-45061",
          "https://errata.almalinux.org/9/ALSA-2023-0953.html",
          "https://errata.rockylinux.org/RLSA-2023:0833",
          "https://github.com/python/cpython/issues/98433",
          "https://github.com/python/cpython/pull/99092",
          "https://github.com/python/cpython/pull/99230 (3.9-branch)",
          "https://github.com/python/cpython/pull/99231 (3.8-branch)",
          "https://linux.oracle.com/cve/CVE-2022-45061.html",
          "https://linux.oracle.com/errata/ELSA-2023-2860.html",
          "https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2AOUKI72ACV6CHY2QUFO6VK2DNMVJ2MB/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/35YDIWCUMWTMDBWFRAVENFH6BLB65D6S/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4WBZJNSALFGMPYTINIF57HAAK46U72WQ/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/63FS6VHY4DCS74HBTEINUDOECQ2X6ZCH/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7WQPHKGNXUJC3TC3BDW5RKGROWRJVSFR/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B3YI6JYARWU6GULWOHNUROSACT54XFFS/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GTPVDZDATRQFE6KAT6B4BQIQ4GRHIIIJ/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IN26PWZTYG6IF3APLRXQJBVACQHZUPT2/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JCDJXNBHWXNYUTOEV4H2HCFSRKV3SYL3/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JTYVESWVBPD57ZJC35G5722Q6TS37WSB/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KNE4GMD45RGC2HWUAAIGTDHT5VJ2E4O4/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LKWAMPURWUV3DCCT4J7VHRF4NT2CFVBR/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O67LRHDTJWH544KXB6KY4HMHQLYDXFPK/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ORVCQGJCCAVLN4DJDTWGREFCUWXKQRML/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PLQ2BNZVBBAQPV3SPRU24ZD37UYJJS7W/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QLUGZSEAO3MBWGKCUSMKQIRYJZKJCIOB/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RDK3ZZBRYFO47ET3N4BNTKVXN47U6ICY/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RH57BNT4VQERGEJ5SXNXSVMDYP66YD4H/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RTN2OOLKYTG34DODUEJGT5MLC2PFGPBA/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T3D5TX4TDJPXHXD2QICKTY3OCQC3JARP/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UHVW73QZJMHA4MK7JBT7CXX7XSNYQEGF/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VCMDX6IFKLOA3NXUQEV524L5LHTPI2JI/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/X3EJ6J7PXVQOULBQZQGBXCXY6LFF6LZD/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XXZJL3CNAFS5PAIR7K4RL62S3Y7THR7O/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YPNWZKXPKTNHS5FVMN7UQZ2UPCSEFJUK/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZB5YCMIRVX35RUB6XPOWKENCVCJEVDRK/",
          "https://nvd.nist.gov/vuln/detail/CVE-2022-45061",
          "https://python-security.readthedocs.io/vuln/slow-idna-large-strings.html",
          "https://security.gentoo.org/glsa/202305-02",
          "https://security.netapp.com/advisory/ntap-20221209-0007/",
          "https://ubuntu.com/security/notices/USN-5767-1",
          "https://ubuntu.com/security/notices/USN-5767-2",
          "https://ubuntu.com/security/notices/USN-5888-1",
          "https://www.cve.org/CVERecord?id=CVE-2022-45061"
        ],
        "PublishedDate": "2022-11-09T07:15:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2023-24329",
        "PkgID": "python3.9-minimal@3.9.2-1",
        "PkgName": "python3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e0ec835c1f88840979da9a3ea10e58ca594d79d44d4e4871cc2e5043eaaa83b8"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-24329",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "urllib.parse url blocklisting bypass",
        "Description": "An issue in the urllib.parse component of Python before 3.11.4 allows attackers to bypass blocklisting methods by supplying a URL that starts with blank characters.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-20"
        ],
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://access.redhat.com/errata/RHSA-2023:3595",
          "https://access.redhat.com/security/cve/CVE-2023-24329",
          "https://bugzilla.redhat.com/2173917",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2173917",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-24329",
          "https://errata.almalinux.org/9/ALSA-2023-3595.html",
          "https://errata.rockylinux.org/RLSA-2023:3591",
          "https://github.com/python/cpython/issues/102153",
          "https://github.com/python/cpython/pull/99421",
          "https://github.com/python/cpython/pull/99446 (backport for 3.11 branch)",
          "https://linux.oracle.com/cve/CVE-2023-24329.html",
          "https://linux.oracle.com/errata/ELSA-2023-3595.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6PEVICI7YNGGMSL3UCMWGE66QFLATH72/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DSL6NSOAXWBJJ67XPLSSC74MNKZF3BBO/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/EM2XLZSTXG44TMFXF4E6VTGKR2MQCW3G/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/F2NY75GFDZ5T6YPN44D3VMFT5SUVTOTG/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GR5US3BYILYJ4SKBV6YBNPRUBAL5P2CN/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/H23OSKC6UG6IWOQAUPW74YUHWRWVXJP7/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JZTLGV2HYFF4AMYJL25VDIGAIHCU7UPA/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LWC4WGXER5P6Q75RFGL7QUTPP3N5JR7T/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MZEHSXSCMA4WWQKXT6QV7AAR6SWNZ2VP/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O5SP4RT3RRS434ZS2HQKQJ3VZW7YPKYR/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OHHJHJRLEF3TDT2K3676CAUVRDD4CCMR/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PEUN6T22UJFXR7J5F6UUHCXXPKJ2DVHI/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PURM5CFDABEWAIWZFD2MQ7ZJGCPYSQ44/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/Q3J5N24ECS4B6MJDRO6UAYU6GPLYBDCL/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QRQHN7RWJQJHYP6E5EKESOYP5VDSHZG4/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RA2MBEEES6L46OD64OBSVUUMGKNGMOWW/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T4IDB5OAR5Y4UK3HLMZBW4WEL2B7YFMJ/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TZH26JGNZ5XYPZ5SAU3NKSBSPRE5OHTG/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/U2MZOJYGFCB5PPT6AKMAU72N7QOYWLBP/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UONZWLB4QVLQIY5CPDLEUEKH6WX4VQMC/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WTOAUJNDWZDRWVSXJ354AYZYKRMT56HU/",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-24329",
          "https://pointernull.com/security/python-url-parse-problem.html",
          "https://security.netapp.com/advisory/ntap-20230324-0004/",
          "https://ubuntu.com/security/notices/USN-5888-1",
          "https://ubuntu.com/security/notices/USN-5960-1",
          "https://ubuntu.com/security/notices/USN-6139-1",
          "https://www.cve.org/CVERecord?id=CVE-2023-24329"
        ],
        "PublishedDate": "2023-02-17T15:15:00Z",
        "LastModifiedDate": "2023-06-16T04:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-3426",
        "PkgID": "python3.9-minimal@3.9.2-1",
        "PkgName": "python3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e0ec835c1f88840979da9a3ea10e58ca594d79d44d4e4871cc2e5043eaaa83b8"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-3426",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: Information disclosure via pydoc",
        "Description": "There's a flaw in Python 3's pydoc. A local or adjacent attacker who discovers or is able to convince another local or adjacent user to start a pydoc server could access the server and use it to disclose sensitive information belonging to the other user that they would not normally be able to access. The highest risk of this flaw is to data confidentiality. This flaw affects Python versions before 3.8.9, Python versions before 3.9.3 and Python versions before 3.10.0a7.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-22"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:A/AC:L/Au:S/C:P/I:N/A:N",
            "V3Vector": "CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
            "V2Score": 2.7,
            "V3Score": 5.7
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
            "V3Score": 5.7
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2021-3426",
          "https://bugzilla.redhat.com/show_bug.cgi?id=1935913",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3426",
          "https://github.com/python/cpython/pull/24285",
          "https://github.com/python/cpython/pull/24337",
          "https://linux.oracle.com/cve/CVE-2021-3426.html",
          "https://linux.oracle.com/errata/ELSA-2021-9562.html",
          "https://lists.debian.org/debian-lts-announce/2021/04/msg00005.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/25HVHLBGO2KNPXJ3G426QEYSSCECJDU5/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BF2K7HEWADHN6P52R3QLIOX27U3DJ4HI/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DQYPUKLLBOZMKFPO7RD7CENTXHUUEUV7/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LM5V4VPLBHBEASSAROYPSHXGXGGPHNOE/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N6VXJZSZ6N64AILJX4CTMACYGQGHHD5C/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QNGAFMPIYIVJ47FCF2NK2PIX22HUG35B/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VPX7Y5GQDNB4FJTREWONGC4ZSVH7TGHF/",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-3426",
          "https://python-security.readthedocs.io/vuln/pydoc-getfile.html",
          "https://security.gentoo.org/glsa/202104-04",
          "https://security.netapp.com/advisory/ntap-20210629-0003/",
          "https://ubuntu.com/security/notices/USN-5342-1",
          "https://ubuntu.com/security/notices/USN-5342-3",
          "https://www.cve.org/CVERecord?id=CVE-2021-3426",
          "https://www.oracle.com/security-alerts/cpujan2022.html",
          "https://www.oracle.com/security-alerts/cpuoct2021.html"
        ],
        "PublishedDate": "2021-05-20T13:15:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-3733",
        "PkgID": "python3.9-minimal@3.9.2-1",
        "PkgName": "python3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e0ec835c1f88840979da9a3ea10e58ca594d79d44d4e4871cc2e5043eaaa83b8"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-3733",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "python: urllib: Regular expression DoS in AbstractBasicAuthHandler",
        "Description": "There's a flaw in urllib's AbstractBasicAuthHandler class. An attacker who controls a malicious HTTP server that an HTTP client (such as web browser) connects to, could trigger a Regular Expression Denial of Service (ReDOS) during an authentication request with a specially crafted payload that is sent by the server to the client. The greatest threat that this flaw poses is to application availability.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-400"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:S/C:N/I:N/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
            "V2Score": 4,
            "V3Score": 6.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "V3Score": 6.5
          }
        },
        "References": [
          "https://access.redhat.com/security/cve/CVE-2021-3733",
          "https://bugs.python.org/issue43075",
          "https://bugzilla.redhat.com/show_bug.cgi?id=1995234",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3733",
          "https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-14-final",
          "https://docs.python.org/3.7/whatsnew/changelog.html#python-3-7-11-final",
          "https://docs.python.org/3.8/whatsnew/changelog.html#python-3-8-10-final",
          "https://docs.python.org/3.9/whatsnew/changelog.html#python-3-9-5-final",
          "https://errata.almalinux.org/8/ALSA-2022-1821.html",
          "https://github.com/python/cpython/commit/3fbe96123aeb66664fa547a8f6022efa2dc8788f (3.6.14)",
          "https://github.com/python/cpython/commit/7215d1ae25525c92b026166f9d5cac85fb",
          "https://github.com/python/cpython/commit/7215d1ae25525c92b026166f9d5cac85fb1defe1 (master)",
          "https://github.com/python/cpython/commit/a21d4fbd549ec9685068a113660553d7f80d9b09 (3.9.5)",
          "https://github.com/python/cpython/commit/ada14995870abddc277addf57dd690a2af04c2da (3.7.11)",
          "https://github.com/python/cpython/commit/e7654b6046090914a8323931ed759a94a5f85d60 (3.8.10)",
          "https://github.com/python/cpython/pull/24391",
          "https://linux.oracle.com/cve/CVE-2021-3733.html",
          "https://linux.oracle.com/errata/ELSA-2022-1821.html",
          "https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-3733",
          "https://security.netapp.com/advisory/ntap-20220407-0001/",
          "https://ubuntu.com/security/CVE-2021-3733",
          "https://ubuntu.com/security/notices/USN-5083-1",
          "https://ubuntu.com/security/notices/USN-5199-1",
          "https://ubuntu.com/security/notices/USN-5200-1",
          "https://www.cve.org/CVERecord?id=CVE-2021-3733"
        ],
        "PublishedDate": "2022-03-10T17:42:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-4189",
        "PkgID": "python3.9-minimal@3.9.2-1",
        "PkgName": "python3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e0ec835c1f88840979da9a3ea10e58ca594d79d44d4e4871cc2e5043eaaa83b8"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-4189",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "ftplib should not use the host from the PASV response",
        "Description": "A flaw was found in Python, specifically in the FTP (File Transfer Protocol) client library in PASV (passive) mode. The issue is how the FTP client trusts the host from the PASV response by default. This flaw allows an attacker to set up a malicious FTP server that can trick FTP clients into connecting back to a given IP address and port. This vulnerability could lead to FTP client scanning ports, which otherwise would not have been possible.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-252"
        ],
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "V3Score": 5.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "V3Score": 5.3
          }
        },
        "References": [
          "https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-3737.json",
          "https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-4189.json",
          "https://access.redhat.com/security/cve/CVE-2021-4189",
          "https://bugs.python.org/issue43285",
          "https://bugzilla.redhat.com/show_bug.cgi?id=2036020",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-4189",
          "https://errata.almalinux.org/8/ALSA-2022-1986.html",
          "https://github.com/python/cpython/commit/0ab152c6b5d95caa2dc1a30fa96e10258b5f188e",
          "https://github.com/python/cpython/commit/0ab152c6b5d95caa2dc1a30fa96e10258b5f188e (master)",
          "https://github.com/python/cpython/commit/4134f154ae2f621f25c5d698cc0f1748035a1b88 (v3.6.14)",
          "https://github.com/python/cpython/commit/79373951b3eab585d42e0f0ab83718cbe1d0ee33 (v3.7.11)",
          "https://github.com/python/cpython/commit/7dcb4baa4f0fde3aef5122a8e9f6a41853ec9335 (v3.9.3)",
          "https://linux.oracle.com/cve/CVE-2021-4189.html",
          "https://linux.oracle.com/errata/ELSA-2022-1986.html",
          "https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html",
          "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-4189",
          "https://python-security.readthedocs.io/vuln/ftplib-pasv.html",
          "https://security-tracker.debian.org/tracker/CVE-2021-4189",
          "https://security.netapp.com/advisory/ntap-20221104-0004/",
          "https://ubuntu.com/security/notices/USN-5342-1",
          "https://ubuntu.com/security/notices/USN-5342-2",
          "https://www.cve.org/CVERecord?id=CVE-2021-4189"
        ],
        "PublishedDate": "2022-08-24T16:15:00Z",
        "LastModifiedDate": "2023-06-30T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2023-27043",
        "PkgID": "python3.9-minimal@3.9.2-1",
        "PkgName": "python3.9-minimal",
        "InstalledVersion": "3.9.2-1",
        "Layer": {
          "DiffID": "sha256:e0ec835c1f88840979da9a3ea10e58ca594d79d44d4e4871cc2e5043eaaa83b8"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-27043",
        "DataSource": {
          "ID": "debian",
          "Name": "Debian Security Tracker",
          "URL": "https://salsa.debian.org/security-tracker-team/security-tracker"
        },
        "Title": "Parsing errors in email/_parseaddr.py lead to incorrect value in email address part of tuple",
        "Description": "The email module of Python through 3.11.3 incorrectly parses e-mail addresses that contain a special character. The wrong portion of an RFC2822 header is identified as the value of the addr-spec. In some applications, an attacker can bypass a protection mechanism in which application access is granted only after verifying receipt of e-mail to a specific domain (e.g., only @company.example.com addresses may be used for signup). This occurs in email/_parseaddr.py in recent versions of Python.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-20"
        ],
        "CVSS": {
          "nvd": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "V3Score": 5.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "V3Score": 5.3
          }
        },
        "References": [
          "http://python.org",
          "https://access.redhat.com/security/cve/CVE-2023-27043",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-27043",
          "https://github.com/python/cpython/issues/102988",
          "https://github.com/python/cpython/pull/102990",
          "https://github.com/python/cpython/pull/105127",
          "https://nvd.nist.gov/vuln/detail/CVE-2023-27043",
          "https://python-security.readthedocs.io/vuln/email-parseaddr-realname.html",
          "https://security.netapp.com/advisory/ntap-20230601-0003/",
          "https://www.cve.org/CVERecord?id=CVE-2023-27043"
        ],
        "PublishedDate": "2023-04-19T00:15:00Z",
        "LastModifiedDate": "2023-06-01T14:15:00Z"
      }
    ]
  },
  {
    "Target": "/cowrie/cowrie-git/etc/cowrie.cfg.dist",
    "Class": "secret",
    "Secrets": [
      {
        "RuleID": "aws-secret-access-key",
        "Category": "AWS",
        "Severity": "CRITICAL",
        "Title": "AWS Secret Access Key",
        "StartLine": 932,
        "EndLine": 932,
        "Code": {
          "Lines": [
            {
              "Number": 930,
              "Content": "# As per https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L50-L65",
              "IsCause": false,
              "Annotation": "",
              "Truncated": false,
              "Highlighted": "# As per https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L50-L65",
              "FirstCause": false,
              "LastCause": false
            },
            {
              "Number": 931,
              "Content": "access_key_id = AKIDEXAMPLE",
              "IsCause": false,
              "Annotation": "",
              "Truncated": false,
              "Highlighted": "access_key_id = AKIDEXAMPLE",
              "FirstCause": false,
              "LastCause": false
            },
            {
              "Number": 932,
              "Content": "secret_access_key = ****************************************",
              "IsCause": true,
              "Annotation": "",
              "Truncated": false,
              "Highlighted": "secret_access_key = ****************************************",
              "FirstCause": true,
              "LastCause": true
            },
            {
              "Number": 933,
              "Content": "#",
              "IsCause": false,
              "Annotation": "",
              "Truncated": false,
              "Highlighted": "#",
              "FirstCause": false,
              "LastCause": false
            }
          ]
        },
        "Match": "secret_access_key = ****************************************",
        "Layer": {
          "DiffID": "sha256:a0c7fe8cccf1220a289d039578e1f3589b9c71f97ac06c3d9f8018fea984ed4c",
          "CreatedBy": "COPY /cowrie /cowrie # buildkit"
        }
      }
    ]
  }
]